### ISSUE TITLE
double click players debug

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-experimental#101]
00:24:DEBUG:Printing STACK TRACE for debugging.
00:24:DEBUG:__ thread (4500) _ |  # | _____________ function _____________ | ticks passed from previous function start
00:24:DEBUG:>>         4500    |  0 |      NetworkManager::processAllInput | +0 
00:24:DEBUG:>>         4500    |  1 |           NetworkInput::processInput | +16 
00:24:DEBUG:>>         4500    |  2 |            NetworkInput::processData | +0 
00:24:DEBUG:>>         4500    |  3 |            NetworkInput::processData | +0 
00:24:DEBUG:>>         4500    |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
00:24:DEBUG:>>         4500    |  5 |         PacketDoubleClick::onReceive | +0 
00:24:DEBUG:>>         4500    |  6 |           CClient::Event_DoubleClick | +0 
00:24:DEBUG:>>         4500    |  7 |            CClient::addCharPaperdoll | +0 
00:24:DEBUG:>>         4500    |  8 |     PacketPaperdoll::PacketPaperdoll | +0 
00:24:DEBUG:>>         4500    |  9 |                 CChar::GetTradeTitle | +0 
00:24:DEBUG:>>         4500    | 10 |                CVarDefMap::GetKeyNum | +0 
00:24:DEBUG:>>         4500    | 11 |                   CVarDefMap::GetKey | +0 
00:24:CRITICAL:Error Pri=2, Code=0xc0000005, Desc='Exception', in SUB: NetworkInput::Message::ProcessMessage()
00:24:DEBUG:1:Parsing Packet len=5 id=0x06 [2018/05/17 00:24:30]
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   06 80 06 d3 ba   

my scripts error sphere_skills.scp
 TITLE=Swords%s

**Comment by drk84** [comment]
Yes it's caused by the %s in the title

**Comment by cbnolok** [comment]
Can't reproduce this bug, is it still happening on your side?

**Comment by Leodinas** [comment]
fix
