### ISSUE TITLE
SPELLS - target ground has a different maximum "range"

### ISSUE THREAD

**Issue by MariusVendetta** [Sphereserver/Source-experimental#117]
for example
```
[SPELL 5]
DEFNAME=s_magic_arrow
NAME=Magic Arrow
SOUND=snd_spell_magic_arrow
CAST_TIME=0.5
RUNES=IPY
RESOURCES=i_reag_sulfur_ash
RUNE_ITEM=i_rune_magic_arrow
SCROLL_ITEM=i_scroll_magic_arrow
FLAGS=spellflag_targ_xyz|spellflag_dir_anim|spellflag_targ_item|spellflag_targ_char|spellflag_harm|spellflag_damage|spellflag_fx_bolt|spellflag_resist
EFFECT_ID=i_fx_fireball_small
EFFECT=5,15
DURATION=0.0
MANAUSE=4
SKILLREQ=MAGERY 10.0
INTERRUPT=0
ON=@Effect
   LOCAL.DAMAGETYPE=(<DEF.dam_physical>|<DEF.dam_magic>)
```

add spellflag_targ_obj and spellflag_targ_xyz to a spell.
put somne coin on the ground (1gp each tile)

**try cast the spell on the coin:**
spell will cast but then will fizzle

**try to cast the spell under the coin:**
spell will not start, and you will get "target not in sight"

same distance, different behaviour

i think it should be related to spellflag_targ_xyz having maximum range of 14 instead of 18 as all magic

**Comment by MariusVendetta** [comment]
What kind of fix has been sent?
It is diffucult to implement max range for any spell and a general value for magery range?

**Comment by cbnolok** [comment]
See the commit referencing this issue, it's easy to do what you want
