### ISSUE TITLE
CRITICAL:Exception, in CWorld::SaveTry()

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#118]
Hi

do anyone knows, how to fix this bug or bad settings of sphere ?
background save settings - disabled
always when i tried to save sphere come out that debug and i cant do save anymore.
https://i.gyazo.com/96ef319bc2bc98be602ee4f426f30938.png

**Comment by cbnolok** [comment]
This appears to be a screenshot from the other branch exe, right?

Il lun 13 ago 2018, 17:13 AtillaG1 <notifications@github.com> ha scritto:

**Comment by AtillaG1** [comment]
im not sure what do you mean.

**Comment by AtillaG1** [comment]
Im using SphereSvr-Win32.zip (v. Latest) - Aug 12th, 2018, 7:15 am
so there is another one ? did not know that.

Then im sorry.
Thank you.
