### ISSUE TITLE
DAMAGE VS ARMOR formula

### ISSUE THREAD

**Issue by Ernest088** [Sphereserver/Source-experimental#121]
Hi, im creating a srv with only old style damage on them (only physical armor and damage) but i have an issue, the damage its the same on 0 of AR or with 150 of AR, its seems the formula of damage its not calculating the armor. 

Il try all the combinations posibles on .INI damage era.

**Comment by AtillaG1** [comment]
have same problem but not even on experimental version. Using our own dmg system, settings in sphere.ini all on 0. But calculating dmg isnt working at all, even it is our own code. :/

**Comment by nefthon** [comment]
> Il try all the combinations posibles on .INI damage era.
I'm waiting for feedback.

> But calculating dmg isnt working at all, even it is our own code. :/

I asume you are creating your own final value for damage, and the real damage received for the other character is not the one you got in your formula, right? Damage done is calculated based on some bonus and then, after @hit trigger, the damage is applied on the character (@gethit), and some internal calculations are done related to armor and some things. If you want to make your damage final, set argn2 |= DAM_GOD, so no other calculations are made.

**Comment by cbnolok** [comment]
Is this still a valid issue?

**Comment by Ernest088** [comment]
Yes

**Comment by cbnolok** [comment]
Are you using COMBAT_ELEMENTAL_ENGINE and/or COMBAT_STACKARMOR? Which CombatDamageEra?
Do you use a custom formula to change the final damage? In that case, are you adding DAM_GOD to ARGN2, as suggested by nefthon?

**Comment by canerksk** [comment]
As far as I understand, a value varying between 7 and 35 percent compared to the old sphere has been entered here. I don't know how this value was entered, but this is exactly where the event you mentioned returns. I'm trying to restore it from here, but it doesn't work.

CCharFight.cpp in 798. line

`
// pre-AOS armor rating (AR)
			pSrc->SysMessagef("Ilk Hasar: %i\n", iDmg);
			const CVarDefCont* iArmorRandPercent = m_TagDefs.GetKey("OVERRIDE.ArmorRandPercent");

			int iArmor = pCharDef->m_defense + m_defense;
			int iRand = Calc_GetRandVal2(7, 35);
			int iArMax = iArmor * iRand / 100;
			int iArMin = iArMax / 2;
			int iDef = Calc_GetRandVal2(iArMin, (iArMax - iArMin) + 1);

			if (iArmorRandPercent > 0)
			{
				iRand = (int)iArmorRandPercent->GetValNum();
				iArMax = iArmor * iRand / 100;
				iDef = iArMax;
			}

`

**Comment by canerksk** [comment]
I am trying to make some changes in the OnTakeDamage function under CCharFight.cpp and adjust the amount of reduced damage with a script, but the problem still persists.

`			// pre-AOS armor rating (AR)
			int iArmorRating = pCharDef->m_defense + m_defense;

			int iArMax = iArmorRating * Calc_GetRandVal2(7,35) / 100;
			int iArMin = iArMax / 2;

			int iDef = Calc_GetRandVal2( iArMin, (iArMax - iArMin) + 1 );
			if ( uType & DAMAGE_MAGIC )		// magical damage halves effectiveness of defense
				iDef /= 2;

			iDmg -= iDef;
			if (iDmg <= 0)
				iDmg = 0;`

my code
`	if (!(uType & (DAMAGE_GOD | DAMAGE_FIXED)))
	{
		// pre-AOS armor rating (AR)
		int iDef = (int)(Args.m_VarsLocal.GetKeyNum("Defence"));
		if (iDef)
		{
			iDmg -= iDef;
		}
	}`
