### ISSUE TITLE
TICK period

### ISSUE THREAD

**Issue by nefthon** [Sphereserver/Source-experimental#125]
TICKS right now are done each 0.1s which is an insane amount of ticks and, in a lot of cases, ticking is done in more than that time, which creates lag.

OSI does ticking each 0.25s and I plan to change ours to that time to.
CONS:
TIMERD will not work as always, since it would tick each 0.25s instead of 0.1, it will cause some delay issues, that's why i'm marking it as deprecated and add a TIMERT, which makes more logic 'TIMER T(tick)'.
PROS:
Walking rubberband on newer clients should dissapear (at least partially) because movement packets are meant to happen each 0.25s too.
Less CPU cycles means more free proccessing available when required, 0.15s will be freed each tick.
Best compatibility with some other packets (walkspeed, etc)

**Comment by nefthon** [comment]
Code is added, probably an ini switch should be added in the future

**Comment by MariusVendetta** [comment]
What happent to swing times?
Different weapons with different swing times and speed will be rounded?
Swing 3.1 to 3.0
And 3.2 to 3.25?

**Comment by nefthon** [comment]
Oh, yeah, forgot to mention it.
Yes, values get rounded up, 3.1 = 3.25, 3.2 = 3.25 ... ,etc

**Comment by MariusVendetta** [comment]
i'm not sure is really a wanted behaviour the change of swings time.
i guess is a good idea to realease this feature only with the switch in the ini
and maybe
the TIMERD and TIMERT to be alias one of eachother working as specified in the ini.
this to not completly destroy the working script.

if you use a TIMERD in the script is like using a TIMERT, depends what is specified in to the ini

meybe a ini settings

TICKTIME=
0 for old tick time
1 for new tick time

**Comment by nefthon** [comment]
It's planned to add a switch on the ini, but it's not as simple since that involves so many changes.
Anyway ... does hurt so much to change from 3.1 to 3.0 or 3.25? it's not a huge delay... You were in a similar problem with tenths of second, what if you want to land your swing in 3.01s? you had to wait until 3.1, it's not a huge difference, however that's why it's HIGHLY WARNED on the revisions.

Let me add one thing more: All the combat formulas are OSI based (excepting old 55x ones), which were created with the 0.25s timers on mind, so we now have more precise combat formulas and damages will be more realistic with an OSI-Like mind. Of course that's not applied to other styles.

Anyway, the ini setting is on our mind, regardless of what I think on this matter, I would've added it already but I encountered big problems with TimerF and it's tick-based code so it's on the TODO list.

**Comment by MariusVendetta** [comment]
will change also magic delays

**Comment by GitMadKing** [comment]
another stuff not taken in consideration  BEFORE get this thing done #132

**Comment by cbnolok** [comment]
After a big timers overhaul, the tick period for periodic timers has been reverted to 0,1 seconds (TICKS_PER_SEC = 10 again). World objects (TIMER property of items, chars, etc) in the past were checked inside a big loop each 1/TICKS_PER_SEC seconds, which checked the timeout for each item in each sector in each map. Now, every worldobj timeout is inserted, sorted by the smallest timeout, in a global list which is polled continuously (not related to TICKS_PER_SEC), so there's not anymore any "tick" and the TIMERT keyword is not needed anymore. For this reason, and because it's easy to get confused by it, TIMERT was removed today. You can use TIMER, TIMERD and the recently added TIMERMS.
