### ISSUE TITLE
Prehit not working

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#128]
Prehit doesnt seem to work, these are my settings: 

CombatFlags=04|040
CombatArcheryMovementDelay=10
CombatDamageEra=1
CombatHitChanceEra=1
CombatSpeedEra=1
SpeedScaleFactor=15000
CombatParryingEra=01|010|080

**Comment by cbnolok** [comment]
Can you confirm it isn't working now?

**Comment by soulless320** [comment]
still seems to not be working. it doesn't swing before the hit. just operates like the normal swing.

**Comment by cbnolok** [comment]
Reported to be working after some commits.
