### ISSUE TITLE
sometimes argo isnt the character killed on=@kill

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#129]
it works without issue sometimes, but then other times argo isn't the character being killed, sometimes it's the character who's doing the killing.

**Comment by MariusVendetta** [comment]
Is not in case of suicide?

Marius

Il Sab 25 Ago 2018, 21:38 soulless320 <notifications@github.com> ha scritto:

**Comment by soulless320** [comment]
no, the character was definitely killed and didn't die on accident.

**Comment by soulless320** [comment]
this is something on my end, argo fires under the on=@kill trigger (not a function inside on=@kill) closing incident
