### ISSUE TITLE
item name color

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-experimental#130]
![image](https://user-images.githubusercontent.com/14990509/44786981-64568200-abc8-11e8-89c9-66005a9f847b.png)
I want to use the default 03b2
Not using a script to implement
is it displayed in white?
Not gray?
Fixed method at
Sphere_msg.scp
// Default settings for Message when clicking on items
IMSG_DEF_COLOR    946
IMSG_DEF_FONT    3
IMSG_DEF_UNICODE  1
IMSG_DEF_UNICODE 1 change IMSG_DEF_UNICODE 0
color work

**Comment by cbnolok** [comment]
I did some tests and the packet is sent correctly, the problem is that is the client who decides the font and the color, regardless of what the server sends.
