### ISSUE TITLE
Critical error -> loading save 32bit

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#131]
Hey, got another problem with latest rls 32bit. Can you please look at this? Also there is no problem with it on 64bit.

> 00:39:Loading E:\save\spheredata.scp...
00:39:CRITICAL:(spheredata.scp,71)std::exception in CServerConfig::LoadResourceSection()00:39:CRITICAL:(spheredata.scp,71)exception.what(): bad array new length
00:39:DEBUG:Printing STACK TRACE for debugging.
00:39:DEBUG:__ thread (0) _ |  # | _____________ function _____________ | ticks passed from previous function start
00:39:DEBUG:>>         0    |  0 |   CServerConfig::LoadResourceSection | +0 <-- exception catch point (below is guessed and could be incorrect!)
00:39:DEBUG:>>         0    |  1 |              CSFileText::WriteString | +0
00:39:DEBUG:>>         0    |  2 |                    CSFileText::Write | +0
00:39:DEBUG:section 'imerFNumbers' args '4,36236821,68'
00:39:Loading E:\save\spherestatics.scp...
00:39:WARNING:'E:\save\spherestatics.scp' not found...
00:39:WARNING:Can't Load E:\save\spherestatics.scp
00:39:Loading E:\save\sphereworld.scp...
00:39:CRITICAL:std::exception in CWorld::LoadWorld()00:39:CRITICAL:exception.what(): bad allocation
00:39:DEBUG:Printing STACK TRACE for debugging.
00:39:DEBUG:__ thread (0) _ |  # | _____________ function _____________ | ticks passed from previous function start
00:39:DEBUG:>>         0    |  0 |              CSFileText::WriteString | +0
00:39:DEBUG:>>         0    |  1 |                    CSFileText::Write | +0
00:39:FATAL:Server terminated: Failed to load worldsave files (code -8)

Also there is block from spheredata.scp

> [TIMERF]
CurTick=2
TimerFCall=remove
TimerFNumbers=0,32363414,81
TimerFCall=remove
TimerFNumbers=0,32363117,337
TimerFCall=remove
TimerFNumbers=0,32362796,593
TimerFCall=f_rockdung_slaveAnim
TimerFNumbers=0,37707259,2
TimerFCall=rockdung_franger_checkwolfhp
TimerFNumbers=0,31819677,3
TimerFCall=f_rockdung_slaveAnim
TimerFNumbers=0,37707259,1
TimerFCall=rockdung_franger_checkwolfhp
TimerFNumbers=0,31819677,4
TimerFCall=remove
TimerFNumbers=1,32363486,6
TimerFCall=remove
TimerFNumbers=1,32363238,196
TimerFCall=remove
TimerFNumbers=1,32363197,262
TimerFCall=remove
TimerFNumbers=1,32363131,316
TimerFCall=remove
TimerFNumbers=1,32362899,518
TimerFCall=remove
TimerFNumbers=1,32362824,572
TimerFCall=rockdung_franger_checkwolfhp
TimerFNumbers=1,31824237,1
TimerFCall=rockdung_franger_checkwolfhp
TimerFNumbers=1,31824237,2
TimerFCall=rockdung_franger_checkwolfhp
TimerFNumbers=1,37410890,2
TimerFCall=rockdung_franger_checkwolfhp
TimerFNumbers=1,37410890,3
TimerFCall=remove
TimerFNumbers=2,32363225,231
TimerFCall=remove
TimerFNumbers=2,32362943,487
TimerFCall=rockdung_adeptswing
TimerFNumbers=2,37466641,1
TimerFCall=rockdung_adeptswing
TimerFNumbers=2,37466641,1
TimerFCall=rockdung_adeptswing
TimerFNumbers=2,37466646,1
TimerFCall=rockdung_adeptswing
TimerFNumbers=2,37466646,1
TimerFCall=rockdung_adeptswing
TimerFNumbers=2,37466651,1
TimerFCall=rockdung_adeptswing
TimerFNumbers=2,37466651,1
TimerFCall=rockdung_adeptswing
TimerFNumbers=2,37466656,1
TimerFCall=rockdung_adeptswing
TimerFNumbers=2,37466656,1
TimerFCall=remove
TimerFNumbers=3,32363396,89
TimerFCall=remove
TimerFNumbers=3,32363328,126
TimerFCall=remove
TimerFNumbers=3,32363313,141
TimerFCall=remove
TimerFNumbers=3,32363088,345
TimerFCall=remove                        ------> line 71
TimerFNumbers=3,32363020,397
TimerFCall=f_summon c_golem_earth,c_golem_crystal,c_golem_water,c_golem_lava
TimerFNumbers=3,32405069,1
TimerFCall=f_rockdung_slaveAnim
TimerFNumbers=3,37708507,1
TimerFCall=rockdung_franger_checkwolfhp
TimerFNumbers=3,39610898,2
TimerFCall=f_rockdung_slaveAnim
TimerFNumbers=3,37708507,2
TimerFCall=rockdung_franger_checkwolfhp
TimerFNumbers=3,39610898,3
TimerFCall=rockdung_lomendilwispcontrol
TimerFNumbers=3,38980388,4

**Comment by AtillaG1** [comment]
There is log from loading save on 64bit, did notice some problem too, but didnt shutdown sphere and continuing loading.

> 00:42:Loading E:\save\spheredata.scp...
00:42:CRITICAL:(spheredata.scp,71)Generic exception, in CServerConfig::LoadResourceSection()
00:42:DEBUG:Printing STACK TRACE for debugging.
00:42:DEBUG:__ thread (0) _ |  # | _____________ function _____________ | ticks passed from previous function start
00:42:DEBUG:>>         0    |  0 |   CServerConfig::LoadResourceSection | +0 <-- exception catch point (below is guessed and could be incorrect!)
00:42:DEBUG:>>         0    |  1 |              CSFileText::WriteString | +0 
00:42:DEBUG:>>         0    |  2 |                    CSFileText::Write | +0 
00:42:DEBUG:section 'imerFNumbers' args '4,36236821,68'
00:42:Loading E:\save\spherestatics.scp...
00:42:WARNING:'E:\save\spherestatics.scp' not found...
00:42:WARNING:Can't Load E:\save\spherestatics.scp
00:42:Loading E:\save\sphereworld.scp...
00:42:WARNING:(sphereworld.scp,48763)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48771)Unknown container gump id 1 for 0176b

**Comment by cbnolok** [comment]
Is it still happening? A lot of things changed since the report.

**Comment by AtillaG1** [comment]
Honestly i dont know, fixed by using 64bits :)

**Comment by cbnolok** [comment]
Can you test with the 32 bits build please?

**Comment by AtillaG1** [comment]
`WARNING:'C:\Sphere\save\spherestatics.scp' not found...
WARNING:Can't Load C:\Sphere\save\spherestatics.scp
Loading C:\Sphere\save\sphereworld.scp...
CRITICAL:std::exception in CWorld::LoadWorld()
CRITICAL:exception.what(): bad allocation
DEBUG:Printing STACK TRACE for debugging.
DEBUG:__ thread (0) _ |  # | _____________ function _____________ | ticks passed from previous function start
DEBUG:>>         0    |  0 |              CSFileText::WriteString | +0 
DEBUG:>>         0    |  1 |                    CSFileText::Write | +0 
FATAL:Server terminated: Failed to load worldsave files (code -8)`

**Comment by AtillaG1** [comment]
WARNING:'C:\Sphere\save\spherestatics.scp' not found...
WARNING:Can't Load C:\Sphere\save\spherestatics.scp
Loading C:\Sphere\save\sphereworld.scp...
CRITICAL:std::exception in CWorld::LoadWorld()
CRITICAL:exception.what(): bad allocation
DEBUG:Printing STACK TRACE for debugging.
DEBUG:__ thread (0) _ |  # | _____________ function _____________ | ticks passed from previous function start
DEBUG:>>         0    |  0 |              CSFileText::WriteString | +0 
DEBUG:>>         0    |  1 |                    CSFileText::Write | +0 
FATAL:Server terminated: Failed to load worldsave files (code -8)

**Comment by AtillaG1** [comment]
ERROR:(sphereCrypt.ini,161)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,162)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,163)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,164)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,165)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,166)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,167)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,168)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,169)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,170)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,171)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,172)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,173)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,174)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,175)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,176)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,177)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,178)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,179)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,180)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,181)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,182)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,183)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,184)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,185)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,186)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,187)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,188)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,189)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,190)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,191)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,192)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,193)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,194)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
ERROR:(sphereCrypt.ini,195)Undefined symbol 'ENC_LOGIN' ['ENC_LOGIN']
Loaded 246 client encryption keys.
Server started on hostname 'Prema-PC'
Monitoring IP 192.168.1.251:2593
WARNING:'C:\Sphere\accounts\sphereaccu.scp' not found...
WARNING:Rename C:\Sphere\accounts\sphereaccu.scp to 'C:\Sphere\accounts\sphereb30a.scp' FAILED code 2?
Loading C:\Sphere\save\spheredata.scp...
Loading C:\Sphere\save\spherestatics.scp...
WARNING:'C:\Sphere\save\spherestatics.scp' not found...
WARNING:Can't Load C:\Sphere\save\spherestatics.scp
Loading C:\Sphere\save\sphereworld.scp...
CRITICAL:ExcType=std::exception in CWorld::LoadWorld()
CRITICAL:exception.what(): bad allocation
DEBUG:Printing STACK TRACE for debugging.
DEBUG:__ thread (0) _ |  # | _____________ function _____________ | ticks passed from previous function start
DEBUG:>>         0    |  0 |              CSFileText::WriteString | +0 
DEBUG:>>         0    |  1 |                    CSFileText::Write | +0 
FATAL:Server terminated: Failed to load worldsave files (code -8)

**Comment by cbnolok** [comment]
You have to update the first part of the spherecrypt.ini to remove the
enc_login error. This won't fix the exception though.

>
