### ISSUE TITLE
Save loading#2 warnings

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#133]
Hello again,
similary with another issue i created earlier, we have one more problem with save loading on version 64bit. Can someone please help ? Thank you.
Errors looks like that:

> 00:42:Loading E:\save\sphereworld.scp...
00:42:WARNING:(sphereworld.scp,48763)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48771)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48779)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48786)Unknown container gump id 1 for 0176a
00:42:WARNING:(sphereworld.scp,48793)Unknown container gump id 1 for 0176a
00:42:WARNING:(sphereworld.scp,48802)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48810)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48818)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48829)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48838)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48846)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48853)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48861)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48869)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48876)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48884)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48892)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48900)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48908)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,48916)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,113924)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,113934)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,113945)Unknown container gump id 1 for 0176b
00:42:WARNING:(sphereworld.scp,113954)Unknown container gump id 1 for 0176a
00:42:WARNING:(sphereworld.scp,113963)Unknown container gump id 1 for 0176a
00:42:WARNING:(sphereworld.scp,115082)Unknown container gump id 1 for 0176a
00:42:WARNING:(sphereworld.scp,115090)Unknown container gump id 1 for 0176a
00:42:WARNING:(sphereworld.scp,115098)Unknown container gump id 1 for 0176a
00:42:WARNING:(sphereworld.scp,138154)Unknown container gump id 282 for 04141
00:42:ERROR:(sphereworld.scp,152393)Invalid skill key: skill_hiding
00:42:ERROR:(sphereworld.scp,153805)Invalid skill key: skill_magery
00:42:ERROR:(sphereworld.scp,157672)Invalid skill key: skill_hiding
00:42:ERROR:(sphereworld.scp,305133)Invalid skill key: skill_wrestling
00:42:ERROR:(sphereworld.scp,314624)Invalid skill key: skill_hiding
00:42:ERROR:(sphereworld.scp,319396)Invalid skill key: skill_archery
00:42:ERROR:(sphereworld.scp,320970)Invalid skill key: skill_archery
00:42:ERROR:(sphereworld.scp,321046)Invalid skill key: skill_archery
00:42:ERROR:(sphereworld.scp,321122)Invalid skill key: skill_archery
00:42:ERROR:(sphereworld.scp,321197)Invalid skill key: skill_archery

Same in spherechars.scp

> 00:42:Loading E:\save\spherechars.scp...
00:42:WARNING:(spherechars.scp,202)Unknown container gump id 1 for 01769
00:42:WARNING:(spherechars.scp,268)Unknown container gump id 1 for 01769
00:42:WARNING:(spherechars.scp,285)Unknown container gump id 1 for 0176a
00:42:WARNING:(spherechars.scp,6161)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6167)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6174)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6181)Unknown container gump id 1 for 0176a
00:42:WARNING:(spherechars.scp,6188)Unknown container gump id 1 for 0176a
00:42:WARNING:(spherechars.scp,6195)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6202)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6209)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6216)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6223)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6230)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6237)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6300)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6309)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6319)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6329)Unknown container gump id 1 for 0176a
00:42:WARNING:(spherechars.scp,6339)Unknown container gump id 1 for 0176a
00:42:WARNING:(spherechars.scp,6349)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6359)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6369)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6378)Unknown container gump id 1 for 0176b
00:42:WARNING:(spherechars.scp,6388)Unknown container gump id 1 for 0176b

Block from sphereworld.scp

> [WORLDITEM i_key_copper]
SERIAL=04289d5e1
MORE1=04289d5e1
CONT=042b327c3   ->>> 48763 LINE --> magic key ring with lot of keys inside metal chest
P=72,73
CONTGRID=255

Block from spherechars.scp

> [WORLDITEM i_key_copper]
SERIAL=042f6277f
ATTR=08
MORE1=04301098b
CONT=0440a1002
P=79,88
QUALITY=153

Block from error with skill

> [WORLDCHAR c_daemon_sword_undead]
CREATE=311
SERIAL=0228ed16
TIMER=0
TAG.armod=05
TAG.owner=024f5cbe
EVENTS=e_summon_destroy
NPC=10
HOMEDIST=7
P=6065,93,22
FLAGS=020000020
ACTION=skill_hiding    ->>> LINE 152393
HITS=1600
STAM=157
MANA=350
FOOD=0
MAXHITS=1600
MAXMANA=350
HOME=6065,93,22
OSTR=700
OINT=209
ODEX=157
OKARMA=-8000
OFAME=4686
Parrying=913
DetectingHidden=1000
Hiding=850
Magery=933
Tactics=1050
Wrestling=971

**Comment by cbnolok** [comment]
1) `Unknown container gump id 1`: It looks that the items 0176b and others have TDATA2=1. TDATA2 is the gump id for a container, and the value 1 is invalid for a container, thus the error.
2) `Invalid skill key: ...` From which sphere version do these saves come from? 56b? Main branch? I don't remember when and if this was changed, but currently you can set ACTION only by using the skill key (HIDING) and not the defname (skill_hiding). Modern saves should already write the action with the skill key. If these are old save files don't worry, because the npcs will lose the action they were doing at the moment of the save but that's all.

**Comment by AtillaG1** [comment]
1) Yes that helped for part of warnings! Now only warnings we have are for gump id 0:

> 21:44:WARNING:(spherechars.scp,202)Unknown container gump id 0 for 01769
21:44:WARNING:(spherechars.scp,268)Unknown container gump id 0 for 01769
21:44:WARNING:(spherechars.scp,285)Unknown container gump id 0 for 0176a
21:44:WARNING:(spherechars.scp,6161)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6167)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6174)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6181)Unknown container gump id 0 for 0176a
21:44:WARNING:(spherechars.scp,6188)Unknown container gump id 0 for 0176a
21:44:WARNING:(spherechars.scp,6195)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6202)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6209)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6216)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6223)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6230)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6237)Unknown container gump id 0 for 0176b
21:44:WARNING:(spherechars.scp,6300)Unknown container gump id 0 for 0176b

2) Yes you are right. It is sphere from 2013-2014, 0.56c - nightly. Ok we will ignore that.

**Comment by cbnolok** [comment]
Yes nothing will be deleted. Try to remove the TDATA2 from the item 0176b.

**Comment by AtillaG1** [comment]
This is our scp for key rings.

> [ITEMDEF 01011]
DEFNAME=i_key_ring
TYPE=T_KEYRING
TDATA2=1
WEIGHT=1
CATEGORY=Provisions - Miscellaneous
SUBSECTION=Keys
DESCRIPTION=Key Ring
RESOURCES=2 i_ingot_iron
VALUE=10
SKILLMAKE=TINKERING 30.0, t_tinker_tools

ON=@DCLICK
	SRC.MESSAGE Drop keys on an empty key ring

> [ITEMDEF 01769]
// Key ring with keys on it
DEFNAME=i_key_ring_1
TYPE=T_KEYRING
TDATA2=1
RESOURCES=1 i_ingot_iron
WEIGHT=1
CATEGORY=Provisions - Miscellaneous
SUBSECTION=Keys
DESCRIPTION=Key Ring w/Keys
DUPELIST=0176a,0176b

When i tried to comment TDATA2, warnings with gump id 1 was solved, but came up warnings with gump id 0.
Also same scp are on old sphere where saves come from.

**Comment by AtillaG1** [comment]
OK FINALLY FIXED. For us its new that every item with gump like containers have to have TDATA3 and 4 with min and max size of gump, otherwise it is warning you.
Coool!
