### ISSUE TITLE
SpeechColorOverride for players.

### ISSUE THREAD

**Issue by nefthon** [Sphereserver/Source-experimental#134]
As for now SpeechColorOverride is defaulted to SAY_DEF_COLOR (inside sphere_msgs.scp) when chars are being created (an override is not something 'default'), so when that defname is changed, the SpeechColorOverride gets into the action and overrides default hue...

.say for players should always follow SAY_DEF_COLOR's color, unless you implicitly modify the SpeechColorOverride for that player.

Right now I can think of changing that default to 0, as it should IMO, but already created characters would have the old value and this will require manual update.

Any better ideA?

**Comment by cbnolok** [comment]
I agree on changing the default to 0, that would be ideal, even if that means a manual update for old players. The sooner we do this, the better imho

**Comment by cbnolok** [comment]
Luckily, there aren't any compatibility issues with previous save files, since SpeechColorOverride was only saved if different from the default value.
