### ISSUE TITLE
Paralyze Field

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-experimental#135]
Paralyze Field
Is there a problem?
When I stand in Paralyze Field, I use the fireball to attack myself.
When I cast a spell to attack myself more than 2 times, Paralyze Field will lose its effect.

**Comment by cbnolok** [comment]
First of all, you shouldn't be able to cast a spell if you're paralyzed. Are you testing with GM mode on?

**Comment by Leodinas** [comment]
Use marco magic
It is possible to cast spells

**Comment by Leodinas** [comment]
field spell are the same problem

**Comment by cbnolok** [comment]
Paralyzation field bug reported to be caused by custom scripts
