### ISSUE TITLE
ARGN2 SPELL @Success & POTION doesn't work

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-experimental#136]
i_potion_Strength
i_potion_StrengthGreat
have same EFFECT.
changing ARGN2 under @SUCCESS of the spell, will however go as value of EFFECT under [SPELL section.

if change to EFFECT=5
potion Strength, potion  Strength Greate, and spell, just get same 5 value rise.
also, argn2 is always, still random. and changing it will not help.

maybe it applies also to other potion/spell like cunning, agility..

**Comment by drk84** [comment]
That's a not bug,
The difference between a greater potion and a normal potion is just the  MORE2 value. 
As i wrote on discord, MORE2 is the magery skill with which the spelll "contained" in the potion (MOREX) will be casted. 

Higher is the magical skill, higher is the chance to get the maximum value from the EFFECT field but if your EFFECT field holds only one value you will always get this single value, so you must have at least two values in the EFFECT field.

In few words, drinking a strength potion with MORE2= 100.0 is like being affected by a  strength spell casted by a GM Mage.

**Comment by GitMadKing** [comment]
As explaind by drk84, that is how should work, so no ISSUE actually exists.

For other who search a solution for define the exact effect of potion, or spell take a look at 
NO DOCUMENTED till now, http://wiki.spherecommunity.net/index.php?title=@Effect
```if <argo.type> == t_potion
 local.effect = 5
endif```

thank you for atention
