### ISSUE TITLE
IsMyPet

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-experimental#137]
IsMyPet not work

**Comment by GitMadKing** [comment]
With a non gm player, does the shrink potion work as expected?
If using the standard script, it uses ismypet. And if working should be
something other.


Standard script:

[ITEMDEF i_potion_Shrink]
ID=i_bottle_white
NAME=Shrink
TYPE=t_potion
TDATA1=i_bottle_empty
RESOURCES=2 i_reag_batwing,1 i_bottle_empty
SKILLMAKE=ALCHEMY 100.0, t_mortar
ON=@Create
   MORE1=s_shrink
   MORE2=100.0
   COLOR=color_gray_lt
ON=@Dropon_char
  obj=<argo>
  IF !(0<obj.ISMYPET>)
    src.sysMESSAGE="<obj.NAME> this is not your pet."
  RETURN 1
  ENDIF
  obj.SHRINK
  remove
  RETURN 1
ON=@DClick
  target="what do you want to shrink?"
  return 1
ON=@TargOn_Char
  IF !<src.targ.ismypet>
    src.sysMESSAGE="<src.targ.NAME> this is not your pet."
    RETURN 1
  ENDIF
  src.targ.SHRINK
  remove
  RETURN 1
ON=@TargOn_Item
  src.sysmessage="Items cannot be shrunk this way"
  return 1


Il Mar 4 Set 2018, 15:15 Breaker <notifications@github.com> ha scritto:
