### ISSUE TITLE
trying to drag corpses

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#142]
When you attempt to drag a corpse on the ground (as a player with no privs) it informs you that you cannot move the corpse. However the corpse is removed from your sight and you have to .update the char before you see it again.

**Comment by cbnolok** [comment]
It seems client related to me. If you disable the GM mode, log out and in again, you won't have this issue anymore. I tried with the main branch and the problem persists. I had a look also at the packets but they seem fine.
