### ISSUE TITLE
sphere crashs when a mount dies

### ISSUE THREAD

**Issue by Crowley91** [Sphereserver/Source-experimental#145]
Sphere is crashing when my mount dies (and sometimes when you try to tame it).

Steps to reproduce the crash (x64 version):
Tame any mount (if you can)
Unmount
Let a monster kills it

It will crash a few seconds after the mount is killed.

I thought it could be related with my scripts, but I tested it with a fresh sphereserver and default scripts and it happened too.

**Comment by cbnolok** [comment]
Still happening?

**Comment by cbnolok** [comment]
Several fixes has been pushed on these days, especially regarding deleted objects and timers. This issue most probably is fixed now. If it's not the case, please reopen the issue.
