### ISSUE TITLE
Sphere crashes after a body is removed

### ISSUE THREAD

**Issue by Crowley91** [Sphereserver/Source-experimental#146]
Sphere is crashing when body timer reaches 0. 

Steps to reproduce the crash:
.add c_dragon (or any npc)
.kill
.xtimer 1
Wait for a few minutes (normally 5-10 minutes)

Tested it with default scripts to make sure it's not any custom scripts causing the crash.

**Comment by cbnolok** [comment]
Still happening?

**Comment by cbnolok** [comment]
Several fixes has been pushed on these days, especially regarding deleted objects and timers. This issue most probably is fixed now. If it's not the case, please reopen the issue.
