### ISSUE TITLE
Sailing not working at all

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#149]
Ships not moving

**Comment by cbnolok** [comment]
Should be fixed with yesterday commit, can you confirm?

**Comment by AtillaG1** [comment]
Not working
When i writed "forward" in console tons of debug spams went up. After i writed "stop" spam stopped and freezes sphere, then it started spamming again :D not sure if it because of sailing or other bug.

**Comment by AtillaG1** [comment]
15:43:CRITICAL:Error Pri=2, Code=0xc0000005, Desc='Exception', in Sphere::Tick() #2 "world"
15:43:DEBUG:Printing STACK TRACE for debugging.
15:43:DEBUG:__ thread (10664) _ |  # | _____________ function _____________ | ticks passed from previous function start
15:43:DEBUG:>>         10664    |  0 |              CSFileText::WriteString | +0 
15:43:DEBUG:>>         10664    |  1 |                    CSFileText::Write | +0 
15:43:DEBUG:Printing STACK TRACE for debugging.
15:43:DEBUG:__ thread (10664) _ |  # | _____________ function _____________ | ticks passed from previous function start
15:43:DEBUG:>>         10664    |  0 |                       CWorld::OnTick | +0 
15:43:DEBUG:>>         10664    |  1 |                   ProfileData::Start | +0 
15:43:DEBUG:Printing STACK TRACE for debugging.
15:43:DEBUG:__ thread (10664) _ |  # | _____________ function _____________ | ticks passed from previous function start
15:43:DEBUG:>>         10664    |  0 |                       CWorld::OnTick | +0 
15:43:DEBUG:>>         10664    |  1 |                   ProfileData::Start | +0 
15:43:DEBUG:Printing STACK TRACE for debugging.
15:43:DEBUG:__ thread (10664) _ |  # | _____________ function _____________ | ticks passed from previous function start
15:43:DEBUG:>>         10664    |  0 |                       CWorld::OnTick | +0 
15:43:DEBUG:>>         10664    |  1 |                   ProfileData::Start | +0 
15:43:DEBUG:Printing STACK TRACE for debugging.
15:43:DEBUG:__ thread (10664) _ |  # | _____________ function _____________ | ticks passed from previous function start
15:43:DEBUG:>>         10664    |  0 |                       CWorld::OnTick | +0 
15:43:DEBUG:>>         10664    |  1 |                   ProfileData::Start | +0 
15:43:DEBUG:Printing STACK TRACE for debugging.
15:43:DEBUG:__ thread (10664) _ |  # | _____________ function _____________ | ticks passed from previous function s

**Comment by AtillaG1** [comment]
Also after placing boat from deed, this errors pop out.
16:17:ERROR:Undefined symbol 't_house_component' ['t_house_component']
16:17:ERROR:Unknown 'EVENTS' Resource 't_house_component'
16:17:ERROR:Undefined symbol 't_house_component' ['t_house_component']
16:17:ERROR:Unknown 'EVENTS' Resource 't_house_component'
16:17:ERROR:Undefined symbol 't_house_component' ['t_house_component']
16:17:ERROR:Unknown 'EVENTS' Resource 't_house_component'
16:17:ERROR:Undefined symbol 't_house_component' ['t_house_component']
16:17:ERROR:Unknown 'EVENTS' Resource 't_house_component'

**Comment by AtillaG1** [comment]
Solved, in our ship scripts we missed:
HEIGHT=3
SPEEDMODE=3
SHIPSPEED=5,1
CAN=can_i_block
REGIONFLAGS=region_flag_nobuilding|region_flag_ship
