### ISSUE TITLE
Stats regen via sphere.ini not working

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#152]
Yes its true. Same with regenvalxxx, both not work.
// Time in seconds for hitpoint regeneration (-1 = no regen)
Regen0=10

// Time in seconds for mana regeneration (-1 = no regen)
Regen1=10

// Time in seconds for stamina regeneration (-1 = no regen)
Regen2=5

Thank you

**Comment by cbnolok** [comment]
Should be fixed in commit 443bf6359da55d4735fffee3c99ce4101c5dff3c.

**Comment by AtillaG1** [comment]
Yes working now.
thank you.
