### ISSUE TITLE
Latest commit, critical, debug

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#154]
11:41:CRITICAL:(zbrane.scp,925)Error Pri=2, Code=0xc0000005, Desc='Exception', in ExcType=CSError in CChar::LoadVal()
11:41:DEBUG:Printing STACK TRACE for debugging.
11:41:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
11:41:DEBUG:(15900)          T_Main |  0 |      NetworkManager::processAllInput | +0 
11:41:DEBUG:(15900)          T_Main |  1 |           NetworkInput::processInput | +16 
11:41:DEBUG:(15900)          T_Main |  2 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  3 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  4 |  NetworkInput::processGameClientData | +0 
11:41:DEBUG:(15900)          T_Main |  5 |       PacketItemPickupReq::onReceive | +0 
11:41:DEBUG:(15900)          T_Main |  6 |           CClient::Event_Item_Pickup | +0 
11:41:DEBUG:(15900)          T_Main |  7 |                    CChar::ItemPickup | +0 
11:41:DEBUG:(15900)          T_Main |  8 |                      CChar::LayerAdd | +0 
11:41:DEBUG:(15900)          T_Main |  9 |                   CChar::OnRemoveObj | +0 
11:41:DEBUG:(15900)          T_Main | 10 |                     CItem::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main | 11 |                     CChar::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main | 12 |          CScriptObj::OnTriggerScript | +0 
11:41:DEBUG:(15900)          T_Main | 13 |          CScriptObj::OnTriggerRunVal | +0 
11:41:DEBUG:(15900)          T_Main | 14 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 15 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 16 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 17 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 18 |                      CClient::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 19 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 20 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 21 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 22 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 23 |                     CChar::r_LoadVal | +0 <-- exception catch point (below is guessed and could be incorrect!)
11:41:DEBUG:(15900)          T_Main | 24 |                       CLog::EventStr | +0 
11:41:DEBUG:(15900)          T_Main | 25 |              CSFileText::WriteString | +0 
11:41:DEBUG:(15900)          T_Main | 26 |                    CSFileText::Write | +0 
11:41:DEBUG:command '40' args ''
11:41:DEBUG:Printing STACK TRACE for debugging.
11:41:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
11:41:DEBUG:(15900)          T_Main |  0 |      NetworkManager::processAllInput | +0 
11:41:DEBUG:(15900)          T_Main |  1 |           NetworkInput::processInput | +16 
11:41:DEBUG:(15900)          T_Main |  2 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  3 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  4 |  NetworkInput::processGameClientData | +0 
11:41:DEBUG:(15900)          T_Main |  5 |       PacketItemPickupReq::onReceive | +0 
11:41:DEBUG:(15900)          T_Main |  6 |           CClient::Event_Item_Pickup | +0 
11:41:DEBUG:(15900)          T_Main |  7 |                    CChar::ItemPickup | +0 
11:41:DEBUG:(15900)          T_Main |  8 |                      CChar::LayerAdd | +0 
11:41:DEBUG:(15900)          T_Main |  9 |                   CChar::OnRemoveObj | +0 
11:41:DEBUG:(15900)          T_Main | 10 |                     CItem::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main | 11 |                     CChar::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main | 12 |          CScriptObj::OnTriggerScript | +0 
11:41:DEBUG:(15900)          T_Main | 13 |          CScriptObj::OnTriggerRunVal | +0 
11:41:DEBUG:(15900)          T_Main | 14 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 15 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 16 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 17 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 18 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 19 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 20 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 21 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 22 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 23 |                     CChar::r_LoadVal | +0 <-- exception catch point (below is guessed and could be incorrect!)
11:41:DEBUG:(15900)          T_Main | 24 |                 CChar::Skill_SetBase | +0 
11:41:DEBUG:(15900)          T_Main | 25 |                    CVarDefMap::Empty | +0 
11:41:DEBUG:command '40' args ''
11:41:CRITICAL:(zbrane.scp,902)Error Pri=2, Code=0xc0000005, Desc='Exception', in ExcType=CSError in CChar::LoadVal()
11:41:DEBUG:Printing STACK TRACE for debugging.
11:41:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
11:41:DEBUG:(15900)          T_Main |  0 |      NetworkManager::processAllInput | +0 
11:41:DEBUG:(15900)          T_Main |  1 |           NetworkInput::processInput | +0 
11:41:DEBUG:(15900)          T_Main |  2 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  3 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  4 |  NetworkInput::processGameClientData | +0 
11:41:DEBUG:(15900)          T_Main |  5 |        PacketItemEquipReq::onReceive | +0 
11:41:DEBUG:(15900)          T_Main |  6 |                     CChar::ItemEquip | +0 
11:41:DEBUG:(15900)          T_Main |  7 |                     CItem::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main |  8 |                     CChar::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main |  9 |          CScriptObj::OnTriggerScript | +0 
11:41:DEBUG:(15900)          T_Main | 10 |          CScriptObj::OnTriggerRunVal | +0 
11:41:DEBUG:(15900)          T_Main | 11 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 12 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 13 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 14 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 15 |                      CClient::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 16 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 17 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 18 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 19 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 20 |                     CChar::r_LoadVal | +0 <-- exception catch point (below is guessed and could be incorrect!)
11:41:DEBUG:(15900)          T_Main | 21 |                       CLog::EventStr | +0 
11:41:DEBUG:(15900)          T_Main | 22 |              CSFileText::WriteString | +0 
11:41:DEBUG:(15900)          T_Main | 23 |                    CSFileText::Write | +0 
11:41:DEBUG:command '40' args ''
11:41:DEBUG:Printing STACK TRACE for debugging.
11:41:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
11:41:DEBUG:(15900)          T_Main |  0 |      NetworkManager::processAllInput | +0 
11:41:DEBUG:(15900)          T_Main |  1 |           NetworkInput::processInput | +0 
11:41:DEBUG:(15900)          T_Main |  2 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  3 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  4 |  NetworkInput::processGameClientData | +0 
11:41:DEBUG:(15900)          T_Main |  5 |        PacketItemEquipReq::onReceive | +0 
11:41:DEBUG:(15900)          T_Main |  6 |                     CChar::ItemEquip | +0 
11:41:DEBUG:(15900)          T_Main |  7 |                     CItem::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main |  8 |                     CChar::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main |  9 |          CScriptObj::OnTriggerScript | +0 
11:41:DEBUG:(15900)          T_Main | 10 |          CScriptObj::OnTriggerRunVal | +0 
11:41:DEBUG:(15900)          T_Main | 11 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 12 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 13 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 14 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 15 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 16 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 17 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 18 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 19 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 20 |                     CChar::r_LoadVal | +0 <-- exception catch point (below is guessed and could be incorrect!)
11:41:DEBUG:(15900)          T_Main | 21 |                 CChar::Skill_SetBase | +0 
11:41:DEBUG:(15900)          T_Main | 22 |                    CVarDefMap::Empty | +0 
11:41:DEBUG:command '40' args ''
11:41:CRITICAL:(zbrane.scp,925)Error Pri=2, Code=0xc0000005, Desc='Exception', in ExcType=CSError in CChar::LoadVal()
11:41:DEBUG:Printing STACK TRACE for debugging.
11:41:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
11:41:DEBUG:(15900)          T_Main |  0 |      NetworkManager::processAllInput | +0 
11:41:DEBUG:(15900)          T_Main |  1 |           NetworkInput::processInput | +0 
11:41:DEBUG:(15900)          T_Main |  2 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  3 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  4 |  NetworkInput::processGameClientData | +0 
11:41:DEBUG:(15900)          T_Main |  5 |       PacketItemPickupReq::onReceive | +0 
11:41:DEBUG:(15900)          T_Main |  6 |           CClient::Event_Item_Pickup | +0 
11:41:DEBUG:(15900)          T_Main |  7 |                    CChar::ItemPickup | +0 
11:41:DEBUG:(15900)          T_Main |  8 |                      CChar::LayerAdd | +0 
11:41:DEBUG:(15900)          T_Main |  9 |                   CChar::OnRemoveObj | +0 
11:41:DEBUG:(15900)          T_Main | 10 |                     CItem::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main | 11 |                     CChar::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main | 12 |          CScriptObj::OnTriggerScript | +0 
11:41:DEBUG:(15900)          T_Main | 13 |          CScriptObj::OnTriggerRunVal | +0 
11:41:DEBUG:(15900)          T_Main | 14 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 15 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 16 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 17 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 18 |                      CClient::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 19 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 20 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 21 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 22 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 23 |                     CChar::r_LoadVal | +0 <-- exception catch point (below is guessed and could be incorrect!)
11:41:DEBUG:(15900)          T_Main | 24 |                       CLog::EventStr | +0 
11:41:DEBUG:(15900)          T_Main | 25 |              CSFileText::WriteString | +0 
11:41:DEBUG:(15900)          T_Main | 26 |                    CSFileText::Write | +0 
11:41:DEBUG:command '40' args ''
11:41:DEBUG:Printing STACK TRACE for debugging.
11:41:DEBUG: __ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
11:41:DEBUG:(15900)          T_Main |  0 |      NetworkManager::processAllInput | +0 
11:41:DEBUG:(15900)          T_Main |  1 |           NetworkInput::processInput | +0 
11:41:DEBUG:(15900)          T_Main |  2 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  3 |            NetworkInput::processData | +0 
11:41:DEBUG:(15900)          T_Main |  4 |  NetworkInput::processGameClientData | +0 
11:41:DEBUG:(15900)          T_Main |  5 |       PacketItemPickupReq::onReceive | +0 
11:41:DEBUG:(15900)          T_Main |  6 |           CClient::Event_Item_Pickup | +0 
11:41:DEBUG:(15900)          T_Main |  7 |                    CChar::ItemPickup | +0 
11:41:DEBUG:(15900)          T_Main |  8 |                      CChar::LayerAdd | +0 
11:41:DEBUG:(15900)          T_Main |  9 |                   CChar::OnRemoveObj | +0 
11:41:DEBUG:(15900)          T_Main | 10 |                     CItem::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main | 11 |                     CChar::OnTrigger | +0 
11:41:DEBUG:(15900)          T_Main | 12 |          CScriptObj::OnTriggerScript | +0 
11:41:DEBUG:(15900)          T_Main | 13 |          CScriptObj::OnTriggerRunVal | +0 
11:41:DEBUG:(15900)          T_Main | 14 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 15 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 16 |             CScriptObj::OnTriggerRun | +0 
11:41:DEBUG:(15900)          T_Main | 17 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 18 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 19 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 20 |                        CChar::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 21 |                     CObjBase::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 22 |                   CScriptObj::r_Verb | +0 
11:41:DEBUG:(15900)          T_Main | 23 |                     CChar::r_LoadVal | +0 <-- exception catch point (below is guessed and could be incorrect!)
11:41:DEBUG:(15900)          T_Main | 24 |                 CChar::Skill_SetBase | +0 
11:41:DEBUG:(15900)          T_Main | 25 |                    CVarDefMap::Empty | +0 
11:41:DEBUG:command '40' args ''

**Comment by cbnolok** [comment]
What's at that line in the script?

**Comment by AtillaG1** [comment]
src.<serv.itemdef.<act.baseid>.skill> -= <eval (<act.tag0.level>-1)*50>
