### ISSUE TITLE
Some NPC got moves like Jagr (spiders spitting flame like dragons)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#155]
Found the problem with some npc's which are not smart enough to be able to do special moves like spitting flames and so on.
When they are loading flame and spitt, they show action 110.

Xun mentioned something about Coruja's news about monsters from C branch.

Can you take a look at this?
Thank you

**Comment by cbnolok** [comment]
Can you give some examples of npcs behaving like that?

**Comment by AtillaG1** [comment]
all spiders, serpents and snakes.
But maybe it is our problem, because we find out that there is change in brains, brain for dragons and monster is with different numbers then earlier with old spheres. We will see today.
