### ISSUE TITLE
ITEM SPAWNS t_spawn_item (new FEATURE)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#156]
I would like to ask you to add feature for item spawn, if i choose distance 0 ----> then spawn item directly on spawn point.
Now it works like it is spawns always 1 tile around spawn, so if you place spawn close to wall, there is chance it will spawns behind static or somewhere where it isnt reachable.

**Comment by WRWRs** [comment]
i need this feature! it work on C, for item 0 = same XYZ with spawner

**Comment by WRWRs** [comment]
work fine
