### ISSUE TITLE
SPEECHCOLOR problem

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#163]
How players can change speechcolor? 
If they changed it ingame
It adding by sphere to saves, but after restart get error mesage about it

**Comment by cbnolok** [comment]
Speechcolor is the hue the client sends to the server when a player talks, then the server records it for that player. The server cannot change client's speech color

**Comment by Seokotov** [comment]
yeah
now players can change it in options and sphere saving in like SPEECHCOLOROVERRIDE=690
but players speech showing always yellow (default)

**Comment by Seokotov** [comment]
need SPEECHCOLOROVERRIDE=0 to old chars
on new work fine
