### ISSUE TITLE
New player starting with TIMER=0 and can't finish any action

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#171]
New player starting with TIMER=0 and can't finish any action, they have TIMER=0 in spherechars
All old players have a TIMER=-1 showing in .info menu and not saved in spherechars

**Comment by Seokotov** [comment]
looks like work fine now

**Comment by Seokotov** [comment]
have problem with new players again
they can't finish any action

**Comment by GitMadKing** [comment]
maybe relate to mine #186  ?

**Comment by Seokotov** [comment]
> maybe relate to mine #186 ?
this problem was fixed 2weeks ago but now active again

**Comment by Seokotov** [comment]
looks like work now :)

**Comment by Seokotov** [comment]
new players can'tfinish any action again :(

**Comment by cbnolok** [comment]
.show uid.playeruid.issleeping and .sector.issleeping?

**Comment by cbnolok** [comment]
Can't replicate here. I created a new player and he can use skills and so on

**Comment by Seokotov** [comment]
> Can't replicate here. I created a new player and he can use skills and so on

don't know why but my players creating again with timer=0 and can't finish any skill
for example try to use anatomy or hiding
but if i restart my sphere, created and saved player work fine 
same problem was in january and it was fixed but now it happen again after manipulations with regions
