### ISSUE TITLE
Weapon not work on Range 0

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#177]
Player can't hit enemy using weapon if Range=0
wrestling is ok
also all monsters go to range 0 and hit player :)
![x2](https://user-images.githubusercontent.com/28328535/50611523-d2e57c80-0ee7-11e9-95e3-91c6fdc1f66d.jpg)

**Comment by GitMadKing** [comment]
wrestling is NOT ok if next to attacker.
also NPC with bare hands does not attack
