### ISSUE TITLE
items dropped on the same spot on the ground placed above

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#183]
items dropped on the same spot on the ground placed above
don't know maybe it's client problem and must be fixed by scripts? 
![x2](https://user-images.githubusercontent.com/28328535/50736888-d58bee80-11d3-11e9-8dd5-01d9ae99fb08.jpg)
you can drop any item with height and build a towers :)

**Comment by Seokotov** [comment]
may be we can add flag for item that can't be placed in same tile?

**Comment by cbnolok** [comment]
There should be an experimental flag for it, have you tried?

**Comment by Seokotov** [comment]
> There should be an experimental flag for it, have you tried?
which flag?

**Comment by cbnolok** [comment]
EF_ItemStacking, is it active?

**Comment by Seokotov** [comment]
// EF_ItemStacking				00000004 // Enable item stacking feature when drop items on ground
disabling it and now work fine
