### ISSUE TITLE
Add EnableOverflowStats option

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#185]
How about to add EnableOverflowStats or something else option.
Now we have a hard limits of main stats STR DEX INT and following mana, stam, hits
Problem we have if want to give to player extra charge of mana for example:
player have int 100 and maxmana 100
i want to give a player charge of 20 mana
so we have 100 int and 120 mana
but when status refreshing mana drop down to maxmana (to 100)
i remember time when in sphere we can set mana 1000 and it dropping to maxmana slow by 1 by tick

So this option may help to make many nice things

**Comment by cbnolok** [comment]
What about a local.canoverflow in @statchange?

**Comment by Seokotov** [comment]
> What about a local.canoverflow in @statchange?

it would be fine i think

**Comment by AtillaG1** [comment]
If it would help us to fix stats lowering while hit by spell and hits above max limit, it would be perfect. Really important for us.

**Comment by AtillaG1** [comment]
I found something in code, when i comment it, my problem is solved. :D 
But it makes another one. My hits,mana,stam are regenerating with no limits :D infinite regens.

CCharAct.cpp
`line 750  	//else if ( iVal > uiLimit )
line 751    	//	iVal = uiLimit;`
