### ISSUE TITLE
sometime hitcheck doesn't trigger

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-experimental#186]
CombatFlags=01|020|040|00100|01000|08000|010000
COMBAT_NODIRCHANGE  COMBAT_DCLICKSELF_UNMOUTS  COMBAT_ALLOWHITFROMSHIP  COMBAT_ARCHERYCANMOVE   COMBAT_SWING_NORANGE  COMBAT_ANIM_HIT_SMOOTH
https://streamable.com/xmuyx
https://streamable.com/dvjdu
ON=@HitCheck
serv.b HitCheck <name> a<argn1> w<weapon.type>
serv.b DB0
ON=@HitTry
serv.b ht <weapon.speed> <ARGN1>

![](https://cdn.discordapp.com/attachments/476635430821953567/532321519129591858/unknown.png)

![](https://cdn.discordapp.com/attachments/476635430821953567/532321677435076618/unknown.png)

create new pg, with @hitcheck under one of his event
try to attack with bow and arrows
it wont :
when attack
i got serv.b HitCheck <name> a<argn1> w<weapon.type>
got one message with arg1 and weapon typ
then HitTry Trigger(modificato)
the nothing more
if unwar and war again,
attack again
yet again the hitcheck with argn 0
again hittry
and so on..

SEEMS LIKE WITH NEWLLY CREATED PG IT DOES NOT ATTACK
WITH OLD PG YES

BUT MAYBE IS JUST A CASE.

**Comment by cbnolok** [comment]
Still happening?

**Comment by GitMadKing** [comment]
seems no
