### ISSUE TITLE
t_multi creating from deed problem

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#189]
t_multi objects creating to target but showing preview to another place
![x](https://user-images.githubusercontent.com/28328535/50980970-f07b9d00-150a-11e9-9f23-d9ace3448565.jpg)

**Comment by GitMadKing** [comment]
here works good 
build 3009 linux debug-build
client 7.0.20.0

**Comment by Seokotov** [comment]
> here works good
> build 3009 linux debug-build
> client 7.0.20.0
> ![image](https://user-images.githubusercontent.com/16067766/51000156-7fe57800-152c-11e9-8455-83e2d1fbef90.png)

can you check it in windows build?

**Comment by cbnolok** [comment]
Tried with latest commit on windows and it's fine

**Comment by Seokotov** [comment]
> Tried with latest commit on windows and it's fine

i have this problem in latest build :(

**Comment by cbnolok** [comment]
Maybe it's a client problem?

**Comment by GitMadKing** [comment]
also in client 7.0.20.0 and build 3011 windows 64bit debug version ALL IS OK

**Comment by Seokotov** [comment]
Can it be a script probllem?

**Comment by AtillaG1** [comment]
i think it is because you dont have play window in top left corner on your game.

**Comment by GitMadKing** [comment]
yep. also on me same, if move game window

**Comment by Seokotov** [comment]
ahah, lol
so, it can be fixed by sphere or i can close problem?
