### ISSUE TITLE
OnRegionTrigger Segmentation fault STACK TRACE

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-experimental#190]
to reproduce:
buy house
place
.debug
enter in his region
remove te worldgembit of the multi while in its region
BANG

VIDEO: https://streamable.com/5apj9

22:41:c:Client connected [Total:1]. . (Connecting/Connected: 1/1).
22:41:DEBUG:c:New Login Handshake Detected. Client Version: 7.0.20.0
22:41:LOGIN: Account madking confirmed!
22:41:c:Login for account 'madking'. . ConnectionType: ServerList.
22:41:DEBUG:c:Login_Relay to server  with AuthId 3886411221
22:41:c:Client disconnected [Total:0]. Account: 'madking'. .
22:41:d:Client connected [Total:1]. . (Connecting/Connected: 1/1).
22:41:LOGIN: Account madking confirmed!
22:41:d:Login for account 'madking'. . ConnectionType: CharList/Game.
22:41:DEBUG:d:xProcessClientSetup for madking, with AuthId 3886411221 and CliVersion 7002000 / CliVersionReported 7002000
22:41:DEBUG:d:Setup_Play slot 0
22:41:d:Character startup for account 'madking', char 'Madking'. .
22:41:FATAL:Segmentation fault
22:41:DEBUG:Printing STACK TRACE for debugging.
22:41:DEBUG: ___ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
22:41:DEBUG:(356460288)          T_Main |  0 |                 NetworkManager::tick | +0 
22:41:DEBUG:(356460288)          T_Main |  1 |                  NetworkThread::tick | +0 
22:41:DEBUG:(356460288)          T_Main |  2 |           NetworkInput::processInput | +0 
22:41:DEBUG:(356460288)          T_Main |  3 |            NetworkInput::processData | +0 
22:41:DEBUG:(356460288)          T_Main |  4 |            NetworkInput::processData | +0 
22:41:DEBUG:(356460288)          T_Main |  5 |  NetworkInput::processGameClientData | +0 
22:41:DEBUG:(356460288)          T_Main |  6 |            PacketCharPlay::onReceive | +0 
22:41:DEBUG:(356460288)          T_Main |  7 |                  CClient::Setup_Play | +0 
22:41:DEBUG:(356460288)          T_Main |  8 |                 CClient::Setup_Start | +1 
22:41:DEBUG:(356460288)          T_Main |  9 |              CClient::addPlayerStart | +0 
22:41:DEBUG:(356460288)          T_Main | 10 |                    CChar::MoveToChar | +0 
22:41:DEBUG:(356460288)          T_Main | 11 |                    CChar::MoveToRoom | +0 
22:41:DEBUG:(356460288)          T_Main | 12 |             CRegion::OnRegionTrigger | +0 <-- exception catch point (below is guessed and could be incorrect!)
22:41:FATAL:Error Pri=1, Code=11, Desc='Segmentation fault', in ExcType=CSError in SUB: NetworkInput::ProcessMessage() ("Message")
22:41:DEBUG:Printing STACK TRACE for debugging.
22:41:DEBUG: ___ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
22:41:DEBUG:(356460288)          T_Main |  0 |                 NetworkManager::tick | +0 
22:41:DEBUG:(356460288)          T_Main |  1 |                  NetworkThread::tick | +0 
22:41:DEBUG:(356460288)          T_Main |  2 |           NetworkInput::processInput | +0 
22:41:DEBUG:(356460288)          T_Main |  3 |            NetworkInput::processData | +0 
22:41:DEBUG:(356460288)          T_Main |  4 |            NetworkInput::processData | +0 
22:41:DEBUG:(356460288)          T_Main |  5 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
22:41:DEBUG:(356460288)          T_Main |  6 |                       CLog::EventStr | +4 
22:41:DEBUG:(356460288)          T_Main |  7 |                    CSFileText::Close | +0 
22:41:DEBUG:(356460288)          T_Main |  8 |                   CSFileText::_Close | +0 
22:41:DEBUG:d:Parsing Packet len=73 id=0x5d [2019/01/10 22:41:51]
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   5d ed ed ed ed 4d 61 64  6b 69 6e 67 00 00 00 00   ]....Madking....
0010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0020   00 00 00 00 00 00 00 00  3f 00 00 00 00 00 00 00   ........?.......
0030   7f 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ...............
0040   00 00 00 00 00 c0 a8 04  01                        .........

[DEBUG_STACK_TRACE.txt](https://github.com/Sphereserver/Source-experimental/files/2747163/DEBUG_STACK_TRACE.txt)

**Comment by cbnolok** [comment]
Is it on linux or windows? Can you reproduce it on windows?

**Comment by cbnolok** [comment]
Have you tried with clean scripts?

**Comment by GitMadKing** [comment]
LAST BUILD 3011
same scripts
on windows SphereX_64bit_debug  **ALL IS OK**
on linux SphereX_64bit_debug   **WE'VE GOT ERROR CAPTAIN**

on windows all is ok, on linux as in the video of first post got errors 
and this logs


```
00:37:DEBUG:1:Parsing Packet len=7 id=0x02 [2019/01/12 00:37:10]
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   02 04 06 00 00 00 00                              .......
00:37:FATAL:Segmentation fault
00:37:DEBUG:Printing STACK TRACE for debugging.
00:37:DEBUG: ___ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
00:37:DEBUG:(2041480960)          T_Main |  0 |      NetworkManager::processAllInput | +0 
00:37:DEBUG:(2041480960)          T_Main |  1 |           NetworkInput::processInput | +0 
00:37:DEBUG:(2041480960)          T_Main |  2 |            NetworkInput::processData | +0 
00:37:DEBUG:(2041480960)          T_Main |  3 |            NetworkInput::processData | +0 
00:37:DEBUG:(2041480960)          T_Main |  4 |  NetworkInput::processGameClientData | +0 
00:37:DEBUG:(2041480960)          T_Main |  5 |         PacketMovementReq::onReceive | +1 
00:37:DEBUG:(2041480960)          T_Main |  6 |                  CClient::Event_Walk | +0 
00:37:DEBUG:(2041480960)          T_Main |  7 |                    CChar::MoveToChar | +0 
00:37:DEBUG:(2041480960)          T_Main |  8 |                    CChar::MoveToRoom | +0 
00:37:DEBUG:(2041480960)          T_Main |  9 |             CRegion::OnRegionTrigger | +0 <-- exception catch point (below is guessed and could be incorrect!)
00:37:DEBUG:Printing STACK TRACE for debugging.
00:37:DEBUG: ___ thread (id) name __ |  # | _____________ function _____________ | ticks passed from previous function start
00:37:DEBUG:(2041480960)          T_Main |  0 |      NetworkManager::processAllInput | +0 
00:37:DEBUG:(2041480960)          T_Main |  1 |           NetworkInput::processInput | +0 
00:37:DEBUG:(2041480960)          T_Main |  2 |            NetworkInput::processData | +0 
00:37:DEBUG:(2041480960)          T_Main |  3 |            NetworkInput::processData | +0 
00:37:DEBUG:(2041480960)          T_Main |  4 |  NetworkInput::processGameClientData | +0 <-- exception catch point (below is guessed and could be incorrect!)
00:37:DEBUG:(2041480960)          T_Main |  5 |         PacketMovementReq::onReceive | +1 
00:37:DEBUG:(2041480960)          T_Main |  6 |                  CClient::Event_Walk | +0 
00:37:DEBUG:(2041480960)          T_Main |  7 |                    CChar::MoveToChar | +0 
00:37:DEBUG:(2041480960)          T_Main |  8 |                    CChar::MoveToRoom | +0 
00:37:DEBUG:(2041480960)          T_Main |  9 |             CRegion::OnRegionTrigger | +0 
00:37:DEBUG:1:Parsing Packet len=7 id=0x02 [2019/01/12 00:37:10]
        0  1  2  3  4  5  6  7   8  9  A  B  C  D  E  F
       -- -- -- -- -- -- -- --  -- -- -- -- -- -- -- --
0000   02 84 07 00 00 00 00                              .......
```

**Comment by GitMadKing** [comment]
confirm working
