### ISSUE TITLE
No teleport animation

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-experimental#192]
when using .TELE or passing Gate/Teleporter or casting spell from book
NO ANIMATION is SHOWN. fire column or smoke
the sound works.
adding defined object in sphere ini fire colum in present

already tried clean sphere windows\linux same "absemce" effect

// Teleport effect for GMs and players. Setting 0 disables the effect
TeleportEffectNPC=0372a
TeleportEffectPlayers=0372a
TeleportEffectStaff=03709
TeleportSoundNPC=01fe
TeleportSoundPlayers=01fe
TeleportSoundStaff=01f3

**Comment by Seokotov** [comment]
yeah
i have no effects too

**Comment by AtillaG1** [comment]
yep, same for GM fire effect when teleporting

**Comment by Seokotov** [comment]
gm effect not flame..why?

**Comment by Seokotov** [comment]
ok now

**Comment by GitMadKing** [comment]
working here
