### ISSUE TITLE
Spawns from save (after first load)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#195]
There si pretty huge problem with spawns after save from 0.56c - nightly, loaded with X sphere.
Every npc which were already spawned is somehow not linked to spawns.
For example, i have spawn of Lich. Amount of liches from thats spawn is 2. I have already spawned two liches from save, but when timer comes to 0, it will spawn another liche, after times comes to 0 agian, it will spawn last one. 
So at the end of the day, there are 4 liches.

**Comment by nefthon** [comment]
Fixed here, can you confirm?

**Comment by AtillaG1** [comment]
Yes fixed! thank you.
