### ISSUE TITLE
Character losing attack after you step behind static once

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#196]
I start attacking NPC, once i step behind static or run out of sight, my character forget that attack and i have to reset war mode and then attack again.
Sometimes same thing happen while fighting face to face. It is hard to reproduce but once it happen 0,1 sec before arrow comes out, then it forgot attack and i have to do same thing as i mention above.

tested with clean sphere and basic scp pack

**Comment by cbnolok** [comment]
Is it happening with archery or melee combat? Which are your combat flags?

**Comment by AtillaG1** [comment]
With archery and melee.
CombatFlags=00020|00100|00040

**Comment by AtillaG1** [comment]
just find out that with combat flag 010000 COMBAT_ANIM_HIT_SMOOTH , it is working correctly i guess

**Comment by shiryux** [comment]
I think in CChar::Fight_CanHit, 
in line 1471 (this is for my own build)
`return IsSetCombatFlags(COMBAT_ANIM_HIT_SMOOTH) ? WAR_SWING_SWINGING : WAR_SWING_EQUIPPING;`
should be
`return IsSetCombatFlags(COMBAT_ANIM_HIT_SMOOTH) ? WAR_SWING_SWINGING : WAR_SWING_READY;`
as the WAR_SWING_EQUIPPING resets the target, and the hit should be always ready (even when out of sight) unless the client cancels or switch target.

**Comment by AtillaG1** [comment]
hmm this bug is fixed, but now i can shoot through static :( 
https://i.gyazo.com/ce1e31eabdaf6d82206538c1bee1ec31.mp4

**Comment by AtillaG1** [comment]
FIXED!!! THANK YA!
