### ISSUE TITLE
Attacking something gray causes it to go criminal when it attacks back

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#199]
when you attack a gray npc in town, it will attack you back then it will be flagged criminal, this is not how it should be. 
![image](https://user-images.githubusercontent.com/17236327/51159019-006de680-1855-11e9-9fda-70a86828b41e.png)

**Comment by Seokotov** [comment]
if you are using 3018 build looks like it's related with #201

**Comment by soulless320** [comment]
This isn't a region issue. a gray creature should never go criminal for attacking you when you are the aggressor
