### ISSUE TITLE
Craft menus problem

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#200]
Craft menus not work properly. We fixed worn showing title #164 but still have other bugs
Now problem, if you add to one level items and submenus

**Comment by AtillaG1** [comment]
![image](https://user-images.githubusercontent.com/25097484/51165249-e279a380-189f-11e9-8ff6-203edf1dd9b3.png)
It looks like this. IF you click on that bow, it will craft kidlings.....

**Comment by GitMadKing** [comment]
OK, AFTER SOME TESTING I found how to replicate:
```
[SKILLMENU sm_BOWCRAFT]
// knife on wood
What do you want to carve the wood into?

ON=i_arrow TEST (TEST)
SKILLMENU=sm_BOWCRAFT2

ON=i_KINDLING <name> (<resmake>)
MAKEITEM=i_KINDLING

ON=i_TORCH <name> (<resmake>)
MAKEITEM=i_TORCH

ON=i_ARROW_SHAFT <name> (<resmake>)
MAKEITEM=i_ARROW_SHAFT

ON=i_bow <name> (<resmake>)
MAKEITEM=i_bow

ON=i_CROSSBOW <name> (<resmake>)
MAKEITEM=i_CROSSBOW

ON=i_crossbow_heavy <name> (<resmake>)
MAKEITEM=i_crossbow_heavy

// ON=i_elven_composite_longbow <name> (<resmake>)
// MAKEITEM=i_elven_composite_longbow

[SKILLMENU sm_BOWCRAFT2]
// knife on wood
What do you want to carve the wood into?

ON=i_elven_composite_longbow <name> (<resmake>)
MAKEITEM=i_elven_composite_longbow
```
RESULT:
![image](https://user-images.githubusercontent.com/16067766/51210853-1ee6e700-1914-11e9-9c5b-58771fa39eab.png)

> i get what inside sm_bowcraft2 as item, insted of i_arrow  and also not the text i entered "TEST (TEST)"
> then on click on elven, i got inside sm_bowcraft2 where i can choose elven composite for crafting


THEN CHANGE TO:
```
[SKILLMENU sm_BOWCRAFT]
// knife on wood
What do you want to carve the wood into?

ON=i_KINDLING <name> (<resmake>)
MAKEITEM=i_KINDLING

ON=i_arrow TEST (TEST)
SKILLMENU=sm_BOWCRAFT2

ON=i_TORCH <name> (<resmake>)
MAKEITEM=i_TORCH

ON=i_ARROW_SHAFT <name> (<resmake>)
MAKEITEM=i_ARROW_SHAFT

ON=i_bow <name> (<resmake>)
MAKEITEM=i_bow

ON=i_CROSSBOW <name> (<resmake>)
MAKEITEM=i_CROSSBOW

ON=i_crossbow_heavy <name> (<resmake>)
MAKEITEM=i_crossbow_heavy

// ON=i_elven_composite_longbow <name> (<resmake>)
// MAKEITEM=i_elven_composite_longbow

[SKILLMENU sm_BOWCRAFT2]
// knife on wood
What do you want to carve the wood into?

ON=i_elven_composite_longbow <name> (<resmake>)
MAKEITEM=i_elven_composite_longbow
```
RESULT:
![image](https://user-images.githubusercontent.com/16067766/51210920-4938a480-1914-11e9-8d25-d4939a893102.png)

**Comment by AtillaG1** [comment]
for me all good.

**Comment by Seokotov** [comment]
fixed

**Comment by Seokotov** [comment]
i have strange problem with Blacksmithing menu
1st lvl armors-weapons-misc
2nd lvl colored armors (submenus)
![x2](https://user-images.githubusercontent.com/28328535/52721956-c7dc3c80-2fbb-11e9-99b2-589ca2161468.jpg)
if i add to script string for mytheril two times i can see mytheril menu icon, and unused
if i comment mytheril strings unused showing instead titanium :)
so it's showing as broken latest (latest that char canmake) submenu

**Comment by cbnolok** [comment]
Is any exception shown?

**Comment by Seokotov** [comment]
no
looks like it show if menu have depth 3 or more..

**Comment by Seokotov** [comment]
heh 

> `[SKILLMENU sm_armor]
Armor & Shields
ON=i_decorative_armor @0 Iron Armor
TEST=BLACKSMITHING iron_armor_skillmake
SKILLMENU=sm_Iron_armor
ON=i_decorative_armor @color_o_Steel Steel Armor
TEST=BLACKSMITHING Steel_armor_skillmake
SKILLMENU=sm_Steel_armor
ON=i_decorative_armor @color_o_Titanium Titanium Armor
TEST=BLACKSMITHING Titanium_armor_skillmake
SKILLMENU=sm_Titanium_armor
ON=i_decorative_armor @color_o_Mytheril Mytheril Armor
TEST=BLACKSMITHING mytheril_armor_skillmake
SKILLMENU=sm_Mytheril_armor`

**Comment by Seokotov** [comment]
it's alive!
