### ISSUE TITLE
something strange with timers region actions

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#201]
for example using carpentry for craft boards
after some successful craft we get a problems

if im going to any guarded town - get message from other special region. (i know looks like scripted problems but it all work fine in 3004 build)

also in 3016 we have strange error with action and timers (happen if you use mining skill for example)

**Comment by cbnolok** [comment]
Could you track the beginning of the issue to a specific build? It would be easier to find the problem

**Comment by Seokotov** [comment]
problem with stop actions starting in 3016
just use mining and player stuck

with region problem only in 3018

**Comment by cbnolok** [comment]
Are you sure you haven't changed anything in your scripts? Can you try with clean scripts? I can't reproduce the mining bug here

**Comment by Seokotov** [comment]
> Are you sure you haven't changed anything in your scripts? Can you try with clean scripts? I can't reproduce the mining bug here

yeah, not changed any scripts, it's only 3016 bug
