### ISSUE TITLE
You can commit custom house changes even they are not proper

### ISSUE THREAD

**Issue by azmanomer** [Sphereserver/Source-experimental#202]
There is a bug when you try to commit not proper changes for custome house like below;
Steps to reproduce this;
Do it like in the picture below and tryo to commit
![resim](https://user-images.githubusercontent.com/13722155/51185776-12996480-18e9-11e9-9a3b-35110b76d344.png)
it ll say "Illegal floor! House not legal, not commiting!"
Then remove only 1 tile from those orange tiles and when you do that the whole floor will dissappear then press commit again. It ll be like this ;
![resim](https://user-images.githubusercontent.com/13722155/51185961-89366200-18e9-11e9-8fbe-104409118f4c.png)

**Comment by azmanomer** [comment]
https://vimeo.com/312764388

**Comment by AtillaG1** [comment]
cant commit https://i.gyazo.com/f720c9d63113158450b3128cd157fe98.png

not able to reproduce it, you sure it isnt script problem ?

**Comment by azmanomer** [comment]
yep its only happening if its fresh floor :)

**Comment by AtillaG1** [comment]
[![Screenshot from Gyazo](https://gyazo.com/9a997d865123df71c28d90d3ed4b4ee8/raw)](https://gyazo.com/9a997d865123df71c28d90d3ed4b4ee8)x

**Comment by cbnolok** [comment]
It should work now
