### ISSUE TITLE
again chars got deleted on garbage collection

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-experimental#212]
#187 
updated from 3018 to 3026
```
00:24:Garbage Collection: started.
00:24:ERROR:GC: Deleted UID=040000236, Defname='i_hair_short', Name='Short Hair'. Invalid code=0x3101 (Object is totally lost, no parent exists).
00:24:ERROR:GC: Deleted UID=040000237, Defname='i_backpack', Name='backpack'. Invalid code=0x3101 (Object is totally lost, no parent exists).
00:24:ERROR:GC: Deleted UID=04000024b, Defname='i_bankbox', Name='Bank Box'. Invalid code=0x3101 (Object is totally lost, no parent exists).
00:24:ERROR:GC: Deleted UID=0261, Defname='c_man', Name='Madking'. Invalid code=0x3101 (Object is totally lost, no parent exists).
00:24:WARNING:Player delete 'madking' name 'Madking'
```

**Comment by Seokotov** [comment]
can't reproduce

**Comment by shiryux** [comment]
I just had the same problem on latest:

22:14:(sphere_triggers.scp,176)Statics data saved (save/spherestatics.scp).
22:14:Garbage Collection: started.
22:14:ERROR:GC: Deleted UID=04000e103, Defname='i_sewing_kit', Name='sewing kit'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e144, Defname='i_cloth_bolt', Name='bolt of cloth'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e146, Defname='i_tinker_tools', Name='tinker's tools'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e149, Defname='i_apron_half', Name='half apron'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e175, Defname='i_ingot_iron', Name='Iron ingot'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e187, Defname='i_pickaxe', Name='Pickaxe'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e19c, Defname='i_hammer_sledge', Name='Sledge Hammer'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e1ad, Defname='i_shoes_plain', Name='shoes'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e1b2, Defname='i_pants_short', Name='short pants'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e1d9, Defname='i_shirt_plain', Name='shirt'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e1da, Defname='i_dagger', Name='Dagger'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e1dc, Defname='i_candle', Name='candle'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e1de, Defname='i_book_sm', Name='book'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e1ea, Defname='i_gold', Name='gold coin'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e221, Defname='i_hair_short', Name='Short Hair'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e261, Defname='i_bankbox', Name='Bank Box'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=04000e295, Defname='i_backpack', Name='backpack'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=0e2ba, Defname='c_man', Name='Juliano'. Invalid code=0x3101 (Object is totally lost, no parent exists).
22:14:ERROR:GC: Deleted UID=0e51b, Defname='c_velociraptor', Name='velociraptor'. Invalid code=0x1204 (Ridden NPC without a mount item).
22:14:ERROR:Stone UID=040014bb1 has mislinked member uid=0e2ba
22:14:ERROR:Garbage Collection: done. Object memory leak 132217!=132216.

**Comment by cbnolok** [comment]
Seems to be caused by the fix for sectors, i think i need to update also the garbage collection code

**Comment by GitMadKing** [comment]
not happenned any more
