### ISSUE TITLE
Newbie gold is not consumed on NPC's TRAIN command

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source-experimental#213]
1. Create a character
2. Ask any NPC to train in some skill.
3. Use the newbie gold.
Result: NPC doesn't take the gold but you get the skill trained.

**Comment by drk84** [comment]
for me too it works fine, i have noticed that if you give more money to the trainer (Ex 51 instead of 41) the remaining 10 golds get dropped on the ground.

**Comment by GitMadKing** [comment]
#176 also here the change problem

**Comment by GitMadKing** [comment]
video here https://streamable.com/3ordd

**Comment by shiryux** [comment]
no idea what, but it looks fixed for some reason?
still change getting dropped to feet but that's a different issue.
