### ISSUE TITLE
wrong emotes problem

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#214]
when players login, they can see emotesfrom other players who in offline and far away
![x2](https://user-images.githubusercontent.com/28328535/51734406-8419a580-2095-11e9-8c3f-e0b6ac7c8e2a.jpg)
![944a268b4656f596](https://user-images.githubusercontent.com/28328535/51734417-8845c300-2095-11e9-89ec-840d0c7bf49e.png)

**Comment by Seokotov** [comment]
still here

**Comment by cbnolok** [comment]
Do you know the precise commit that caused this bug? It would be nice if you could roll back some commits ago to check if it's working, since i can't replicate it

**Comment by Seokotov** [comment]
if it's happen i'll let you know

**Comment by Seokotov** [comment]
it's happen again in 3030
after sphere was stucked(players cant cath fish - respawn not creating) and rebooted 
https://media.discordapp.net/attachments/451768815831875596/539851311273869322/6726c767799b5fbe.png?width=1105&height=622

**Comment by cbnolok** [comment]
If sphere "stucks" again please check if the players having problems have issleeping or sector.issleeping == 1 or 0. In any case, i need a way to reproduce your problem

**Comment by Seokotov** [comment]
emotes happen if you staying near offline players after sphere restart

**Comment by cbnolok** [comment]
Can you test it again with latest commit?

**Comment by Seokotov** [comment]
if find some, i'll let you know
