### ISSUE TITLE
When closing a dialog from a memory item under @timer the dialog doesnt close all the way

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#219]
if you close the dialog for a player under @timer it will still show the dialog as open when doing .show isdialogopen

![image](https://user-images.githubusercontent.com/17236327/52316920-b9729d00-298b-11e9-862d-32b375f9dd7c.png)

**Comment by GitMadKing** [comment]
use cont.closedialog (if equipped)
not only closedialog

**Comment by soulless320** [comment]
It's already closing it correctly, the issue however is that it still shows on 'isdialogopen' that it's not closed out

`on=@timer
if (<more1> <12) && (<def0.welcome_dialog_animated>)
  more1 += 1
  trysrc <link> dialogclose d_welcome
  trysrc <link> dialog d_welcome
endif
timerms=75
return 1`

**Comment by soulless320** [comment]
Fixed, thank you Shiryux!
