### ISSUE TITLE
NUKE nukes also CHARS

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-experimental#220]
nuke command also nukes chars

nuke should remove only items

for chars

nukechar is the command, and it works well

**Comment by Seokotov** [comment]
mu nuke note removing chars, only items

**Comment by GitMadKing** [comment]
build?
i'm using 3033

**Comment by soulless320** [comment]
Sounds like maybe it is just removing the spawn item that the char is linked to. When that happens it removes the spawned NPCs as well.

**Comment by Seokotov** [comment]
yes, my chars not removing...only if you nuke spawner item

**Comment by GitMadKing** [comment]
ok. i "didn't" but did nuke spawn item.
i was with gm so when nukeing i did no see no spawn even if there was there
