### ISSUE TITLE
Stats After Curse,Weaken etc.. (Feature request ??)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#222]
Hi, we found another problem, on our live server 0.56c-nightly we are used to stats workign like that:
100str = 100hits, when someone cast Weaken on me, stats are fe. 88str = 100 hits (hits without connection to str in this case)

Now it is work that after weaken your stats are 88str = 88 hits instantly, (connection)

Please can you make some feature for it ? 
We found the code for it, when i comment it as bellow, it works as we need.
https://pastebin.com/TaZ4NS7A

https://pastebin.com/m5chry2a

It is in CCharStat.cpp

**Comment by Seokotov** [comment]
we are told about it in #185

**Comment by AtillaG1** [comment]
it is not the same mate. One is lowering stats on Maxhits, the Weaken spell is lowering stats on Maxhits too after the change.
Nolok send me fix for first problem, but its not fixing the second. Thank why im mentioning this aswell.

**Comment by Seokotov** [comment]
ahh, ok
i hate that stats spells unequip all items if it's required str is more

**Comment by AtillaG1** [comment]
done. Working perfectly.
