### ISSUE TITLE
Players can hearall even though I turned hearall off on everyone

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#227]
Players can hear all things i say even though hearall is off

![image](https://user-images.githubusercontent.com/17236327/52669410-fc7cc500-2ee3-11e9-82a5-d12c3160f56d.png)

**Comment by cbnolok** [comment]
Is that an old account or a new one? Because some months ago (kinda) there was a bug which set on every new account the hearall priv flag.

**Comment by Seokotov** [comment]
it's a transfer from corujas build problem
check privs

**Comment by soulless320** [comment]
they have hearall off.  Also they are only able to hear GMs and players can't hear each other.

**Comment by Seokotov** [comment]
just stop server
open sphereaccu and fix PRIV

**Comment by soulless320** [comment]
it was my gm account set to priv 02a, thanks Seokotov
