### ISSUE TITLE
players do not update when they logout, they stay lingering on the screen

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#228]
![image](https://user-images.githubusercontent.com/17236327/52675891-3d7dd500-2ef6-11e9-95d7-db70ff88eea2.png)

still appearing even though logged out

**Comment by cbnolok** [comment]
What's value for the ini setting ClientLinger?

**Comment by Seokotov** [comment]
yeah i have same, players log out but screen not updating
if you go away and back - he disappearing

**Comment by soulless320** [comment]
Fixed, thank you Nolok!
