### ISSUE TITLE
corpses and other dropped items in sleeping sector not updating with decay timer

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#229]
corpses and other dropped items in sleeping sector not updating with decay timer

if player run around sector he can see old corpse, but if enter to these sector - corpse removing and showing (or may be respawn) live monster
anyway its looks like a bug

**Comment by cbnolok** [comment]
Still happening?
Can you explain it better? The sector awakens when a gm walks in, but not a player?

**Comment by Seokotov** [comment]
yeah, still here
players can see it too

**Comment by Seokotov** [comment]
looks like fixed
