### ISSUE TITLE
Ogre/Ettin/Cyclops NPCs won't attack throwing rocks 

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#231]
Ogre/Ettin/Cyclops NPCs won't attack throwing rocks anymore
i saw it month ago, but forget..now i can see that coruja fixed it in C-source ))))

**Comment by cbnolok** [comment]
That commit blocked that behavior for those monster, so i can't see what's to be "fixed"

**Comment by Seokotov** [comment]
ahh, I just want to able throwing rocks for trolls-ogres/ettins
it's not work like it was always

**Comment by cbnolok** [comment]
From the 56d changelog: "If you want them to keep throwing rocks just set THROWOBJ/THROWDAM/THROWRANGE properties on these chardefs scripts"

**Comment by Seokotov** [comment]
ahh, missed it...ok
thnx
