### ISSUE TITLE
Lag on vendor restock with too many buy templates

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#237]
**it seems like when an NPC has several buy templates, or a buy template that has other buy templates nested inside of it, it will lag heavily during restock, very noticeable.  this causes lots of lag. this particular example is the c_h_provis**
![image](https://user-images.githubusercontent.com/17236327/53403270-4e602900-3981-11e9-8b83-0539f027c2fa.png)

**but this is okay**

![image](https://user-images.githubusercontent.com/17236327/53403285-54eea080-3981-11e9-963e-ad4dcfc50e50.png)

**Comment by cbnolok** [comment]
Can you try if it's only one template in particular?

Il mar 26 feb 2019, 10:45 soulless320 <notifications@github.com> ha scritto:

**Comment by soulless320** [comment]
[TEMPLATE VENDOR_B_PROVISIONER]

the blacksmith had a templrate that was causing an issue as well but i cant be certain which one that was. I know the provis  template was causing lag for sure

**Comment by soulless320** [comment]
This is only in the debug version it seems, perhaps this can be closed if you would like?

**Comment by cbnolok** [comment]
Nope it's still worth checking

>

**Comment by cbnolok** [comment]
I tried to create and dupe provisioners but even on the debug build it doesn't appear to lag here, maybe something related to a custom @create trigger or such?

**Comment by soulless320** [comment]
I will take a look at see if I can find something exact causing this. Ill test it on both a fresh version and mine locally

**Comment by soulless320** [comment]
cant seem to recreate this at all, seems like it was something on my server specifically at the time of using the debug.
