### ISSUE TITLE
the Price property doesnt seem to be respected by vendors when selling to them

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#238]
![image](https://user-images.githubusercontent.com/17236327/53404562-ea8b2f80-3983-11e9-8845-858e2e1c0aea.png)
![image](https://user-images.githubusercontent.com/17236327/53404619-0bec1b80-3984-11e9-88cf-a95473f0d4c4.png)
![image](https://user-images.githubusercontent.com/17236327/53404630-11496600-3984-11e9-9759-9dc825776dc8.png)

**Comment by soulless320** [comment]
im still having troubles with this 
![image](https://user-images.githubusercontent.com/17236327/53507264-92d4ed00-3a85-11e9-9404-9e7ac8ea5628.png)

**Comment by cbnolok** [comment]
Tried with clean scripts?

**Comment by soulless320** [comment]
I pulled from the last commit and restarted the server, vendors now respect the price attr on items. Thanks Nolok!
