### ISSUE TITLE
Issue with stopping swinging 

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#242]
Sometimes players can't hit npcs at all, or lose their swing in the middle of combat. I've seen this issue arise many times and not entirely certain what the problem is.

**Comment by cbnolok** [comment]
Which combatflags? Attacking with weapons only or also unarmed? Melee, ranged or both?

**Comment by soulless320** [comment]
i was just speaking with someone else they've encountered this same problem. I get nothing on the console, players just  stop swinging and they dont ever hit that target again. they have to switch to another target and come back later to finish that one off. 

weapons only, just melee so far i've noticed. 
'''CombatFlags=01|040|0100
CombatArcheryMovementDelay=5
CombatDamageEra=2
CombatHitChanceEra=2
CombatSpeedEra=2
SpeedScaleFactor=40000
CombatParryingEra=01|010|080
'''

**Comment by AtillaG1** [comment]
Its been already in talks and fixed. But probably not for every sphere.ini settings.

Just want to remind it.
https://github.com/Sphereserver/Source-experimental/issues/217

**Comment by soulless320** [comment]
It seems no matter what settings I have , I get complaints from players about this issue fairly frequently.

**Comment by soulless320** [comment]
So i made a fix, and this solves it every time. It also solves the not being able to cast issue

```
[function swingfix]
local.p=<p>
go 1,1,1,0
go <local.p>
```

**Comment by cbnolok** [comment]
Any clue on how to replicate it easily?

**Comment by cbnolok** [comment]
What's your AttackerTimeout in the ini? Does this bug occur after some time during the fight, or can it happen both after 10 seconds and 3 minutes, as example? Is the loss of line of sight involved?

**Comment by AtillaG1** [comment]
Something similar started happening to us aswell. For example i am shooting monster with bow A. After 5 minutes i switch to bow B. Then my attack is canceled, this is ok. But then im not able to even start attacking that npc again. Im dclicking as hell and the npcs is not even colored to all red, which happen if you attacking someone. You can attack only by magic.

**Comment by cbnolok** [comment]
What's your attackertimeout?

**Comment by AtillaG1** [comment]
300

so 8. 6. 2019 v 9:42 odesílatel cbnolok <notifications@github.com> napsal:

**Comment by AtillaG1** [comment]
300

**Comment by cbnolok** [comment]
Is it still happening or is it an old bug? Because i think i recently fixed the one reported by @soulless320

**Comment by AtillaG1** [comment]
im not sure but i havent problems with stop swinging anymore. Only that one i described above.

**Comment by cbnolok** [comment]
This was fixed some time ago, can't remember the commit, but the problem was in the fact that the players didn't always awake the sector they entered.
