### ISSUE TITLE
Players hearing what happens to my gm, and can read what i say miles away

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#243]
Players in britain can hear my GM attacking monsters, getting spells casted on him in deceit. If a player is in moonglow and im fishing they can hear the noises I hear. If I talk in green acres every player can hear me anywhere in the world. If i set account.priv=0 it stops but account.priv=2 makes it so everyone can hear my gms actions/sounds and read what he says.

**Comment by Seokotov** [comment]
just stop your sphere
open sphereaccu and change priv to 0
it's not a bug of sphere it'sbug of your old saves

**Comment by cbnolok** [comment]
Not a bug, 02 is the hearall priv

**Comment by soulless320** [comment]
I don't ever recall hearall making your character broadcast everything across the world that he says, and allow other people to hear sounds that you hear.  and a gm should be able to hearall anyways without this sort of issue.  I think perhaps Seokotov you're talking about something different. All my player accounts are priv 0 already. this pertains only to the GM account. however just for clarification purposes heres the account, and below is a screenshot of this gm account with gm on after setting privs to 0.

[soulless]
PLEVEL=Owner
PRIV=0                  
RESDISP=8

![image](https://user-images.githubusercontent.com/17236327/53562155-a1231780-3b1e-11e9-83a1-67c062226232.png)

now here's on a fresh install of sphere nightly 64 x-1 compiled on feb 27 2019

![image](https://user-images.githubusercontent.com/17236327/53563036-e9dbd000-3b20-11e9-8d1b-10f17aaebb58.png)

the gm account started as 0 priv to begin with, i set it to 0 to make sure in game and all you have to do  turn gm on, and boom, you're broadcasting to the entire world when you talk, and every player hears the noises you hear. you turn gm off, and this all stops.

**Comment by soulless320** [comment]
Thanks Nolok, I apologize for Seokotovs inability to read ;)
