### ISSUE TITLE
 local.ItemDamageChance doesnt seem to respect the shield layer

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#244]
using local.ItemDamageChance on=@get hit and on=@hit doesnt seem to respect the shield, so shields still get damaged rather quickly regardless of this setting.

**Comment by cbnolok** [comment]
The code in @GetHit is the same for every layer, maybe local.ItemDamageLayer is always/often set to 2?

**Comment by soulless320** [comment]
so if i did on@=gethit
local.itemdamagechance=0

the shield would not be damaged at all? because right now my shield will get damaged even though the damage chance is 0

**Comment by cbnolok** [comment]
Is that happening with clean scripts?

Il dom 3 mar 2019, 18:29 soulless320 <notifications@github.com> ha scritto:

**Comment by drk84** [comment]
Shield (or the weapon used for parrying) is damaged when a parry is succesfull.

**Comment by soulless320** [comment]
I think @hitparry would be good. that would also help with my combat script.

**Comment by cbnolok** [comment]
I like the idea of that trigger!

**Comment by soulless320** [comment]
Thanks Nolok, ACE!
