### ISSUE TITLE
when a player gets weaken cast on them they drop items to the ground

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#245]
When you get weakened / cursed and your strength becomes too low for items you are already wearing, you will unequip them, but since you can't put them in your bag they drop to the ground. You should not unequip work items after being weakend below the streq.

**Comment by cbnolok** [comment]
Afair, every item has always been unequipped if char went below strreq, it should be the desired behavior

**Comment by soulless320** [comment]
If it doesn't throw the items to the ground , that i can confirm has never been how it works. Players are quite irritated by it as well

**Comment by cbnolok** [comment]
But are they overloaded or not?

Il dom 3 mar 2019, 08:46 soulless320 <notifications@github.com> ha scritto:

**Comment by soulless320** [comment]
They are overloaded, but it never drops the stuff to the ground, it should be placed inside the pack

**Comment by cbnolok** [comment]
So, it seems that the current behavior has been added on 56c (on 56b items were dropped in the pack if you already carried them). I think we may add an option flag

**Comment by soulless320** [comment]
I think that would be good. The default should be the pack, but either way as long as we control it I would love it, this is a very frustrating thing to have happen when you are weakened and no one's expecting it to happen :O

**Comment by soulless320** [comment]
Good to go, thank you Nolok, sorry for the late reply!
