### ISSUE TITLE
Prehit does not work in combat

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#250]
still have to wait for swing first, then it hits, instead of hitting then delaying the swing.
```
CombatFlags=01|040|0100
CombatDamageEra=0
CombatHitChanceEra=0
SpeedScaleFactor=15000
```

**Comment by cbnolok** [comment]
Actually you need to wait only 1 second, which is the minimum possible duration for the attack animation, and it's intended to work like that, you don't wait the recoil time but only the swing one

**Comment by soulless320** [comment]
Nolok I'm not sure if you saw the discord chat, me and Drk tested it its not working correctly for either of us.  :O the initial attack takes longer than 1 second, then with COMBAT_RECOIL_NORANGE  that doesnt seem to work either, it's not starting the next swing until you come back in range, then you can leave again and come back to hit. 

typically on OSI the first strike was instant, not a 1 second delay, i just tested that to confirm a few days ago.

**Comment by soulless320** [comment]
somewhat not related at all but more bothersome to me personally, with COMBAT_RECOIL_NORANG it does the first hit even if you are in range or not.

**Comment by soulless320** [comment]
it seems like if we are able to get the firsthit_instant to work, then people will be able to emulate the OSI combat system pretty closely. right now the first hit is not instant with that flag enabled.

**Comment by soulless320** [comment]
looks like enabling prehit, and firsthit_instant (which should replicate OSI), firsthit never seems to work. but prehit is working fine.
