### ISSUE TITLE
NPCs with mt_swim cannot walk on water statics

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#253]
They can walk on t_water terrain but not t_water statics 
![image](https://user-images.githubusercontent.com/17236327/53952754-a7297300-409f-11e9-9035-e4f814333eb2.png)

**Comment by cbnolok** [comment]
Do you have a itemdef script for those water tiles? If yes, what is their CAN property?

**Comment by soulless320** [comment]
It's scripted and has  CAN_I_WATER 02

**Comment by soulless320** [comment]
Confirmed the fix, thank you Nolok, you are a saint.
