### ISSUE TITLE
Blood color doesnt work properly when hitting monsters

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#254]
BLOODCOLOR=0596

xshow bloodcolor returned 0596

shows up as black when hitting them in combat

![image](https://user-images.githubusercontent.com/17236327/53972343-980cea00-40cc-11e9-8cda-8c3a0b043803.png)

**Comment by Seokotov** [comment]
#206

**Comment by soulless320** [comment]
I saw that @Seokotov , im not sure why you closed it without it being fixed... He says bloodcolor=2007 works, you say bloodcolor=2007 doesnt work, then you closed it :laughing:  

bloodcolor=2007
![image](https://user-images.githubusercontent.com/17236327/54286721-bbc3aa80-457a-11e9-8b53-2eaa24528135.png)

**Comment by Seokotov** [comment]
yeah, it work only in range and only for fixed value
it was broken everywhere and fixed for some values in range, so  we can use it
we told about limit for value in discord..

**Comment by soulless320** [comment]
Fixed, thanks Nolok!
