### ISSUE TITLE
NPCs are able to spawn into areas they cannot move in

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#255]
These monsters appear to think they can move, but they are infact not able to move
![image](https://user-images.githubusercontent.com/17236327/54107085-88ccbb80-43ae-11e9-8f02-108d2984e8ff.png)

**Comment by cbnolok** [comment]
Which can flags? What's the issue here, precisely? Npcs not moving or being able to spawn there?

**Comment by Seokotov** [comment]
possible to disable for spawn items on water for example?

**Comment by AtillaG1** [comment]
i think npcs spawns only on spawn will help. It works like that on old spheres.
Now you set distance and they spawn in that distance randomly.

**Comment by soulless320** [comment]
Npcs being able to spawn there is the issue. they just end up being stuck and canmove seems to return a result suggesting they should be able to move. This is a pretty common sight on my server, eventually an npc will get spawned into a spot like that.

**Comment by AtillaG1** [comment]
Of course it would be good like that!!
But im not sure if its possible to fix it like that. Maybe you can fix that it will not spawn on static tiles, but what if npcs will spawn on 1 tile without static, but around that tile is only static and no access to that tile ? For example in dungeon behind some rocks and that one tile is behind them in spawn distance.

**Comment by cbnolok** [comment]
Was it fixed by the last commit?

**Comment by soulless320** [comment]
no, but maybe there is nothing to be done? i could make a custom function that checks spawned npcs  once every 24 hours that checks to see if they are stuck and will return them to their spawnpoint if so. Technically the tile this earth elemental is standing on is legitimate. but the w, n, e, and s tiles are blocked and he is boxed in and cannot move. 
![image](https://user-images.githubusercontent.com/17236327/55628713-6cd6f280-577f-11e9-9427-a83c74770786.png)

**Comment by AtillaG1** [comment]
yep, thats what im talking about :( thats why it is not correct like that for me, because it is forcing everyone to do external script as you said to check if its blocked, and then do something. Thats not ideal i would say.

**Comment by cbnolok** [comment]
How is it going now?
