### ISSUE TITLE
Multi components are sent as player reaches them.

### ISSUE THREAD

**Issue by JulianUO** [Sphereserver/Source-experimental#257]
Hi,
This might be confusing.
When you have a multi in view range (with components) the server sends the items as they enter in my view range. This could be okay if you have no item to "override" any item from the multi. 

I tried to override the foundation level with a scripted solution. It was succesful, at first.
Client displays items as they are sent by the server.

So, to achieve this, server should send in this order:
1. Multi item
2. Components

Instead of whatever comes in range first.

**Comment by cbnolok** [comment]
Can you send a gif? I can't understand well what's happening here

**Comment by JulianUO** [comment]
Code used: https://pastebin.com/S8QjWbY1
Graphic description: https://i.imgur.com/raY3Vnx.gif

As you can see, when I remove the multi (by nuking only the main item) all the components get removed, as they are added as component. Some are displayed on the radar, but they are sent before the multi, so the char won't really see them.

**Comment by cbnolok** [comment]
In the latest commit i added some commented code in CClientMsg.cpp that ideally should fix this issue, but that isn't happening for the weird reasons i've added in the comments. I did a lot of tests and tried different approaches, but i wasn't able to fix this and at this point i wonder if it's even possible
