### ISSUE TITLE
Hard Coded request for another combat ERA

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#259]
Around T2A and Renaissance  this was the combat system, please hardcode this system as an option for combat. 
http://web.archive.org/web/20000306053659/http://uo.stratics.com/combat.htm#7

**Comment by JulianUO** [comment]
I did something like that. Sphere has these "percents" but for adding armor. I think 55r worked like this for hit damage, since most of the code I used was grabbed from there. It is hard to balance though.

**Comment by drk84** [comment]
The numbers are different but I think it's already implemented (combatDamage era 0 ) there is even a wiki page about that  

https://wiki.spherecommunity.net/index.php/Armor_Calculation
