### ISSUE TITLE
Issues with Z level

### ISSUE THREAD

**Issue by JulianUO** [Sphereserver/Source-experimental#262]
Since the last update, I'm having troubles walking on some points, or even teleporting.
It happens on multis and statics.

Here you have some footage about the issue: 
First gif, I used .fix.
https://i.imgur.com/dtTL8Z5.gifv

Second gif, just teleport.
https://i.imgur.com/ftcUar4.gifv

It's related to the fix of npcs with mt_swim not able to walk on water.

**Comment by JulianUO** [comment]
NOTE: Unable to reproduce with player account. Only when .GM is enabled.

**Comment by soulless320** [comment]
Confirmed , as a GM when going through teleporters my chars z level seems to go to the base terrain. or teleporting onto a roof I end up at the ground z level for the terrain and not the statics on top.

**Comment by Seokotov** [comment]
teleport to player via admin menu same problem - falling tru the floor, but players stay in this point fine

**Comment by AtillaG1** [comment]
Confirmed. Also my sphere crashed once i tried teleport as a GM on player via admin menu. No errors or anything.

**Comment by Seokotov** [comment]
players falling tru the stairs now

**Comment by soulless320** [comment]
confirmed they get stuck in stairs and can't walk up them.

**Comment by soulless320** [comment]
Seems fixed in the latest version you sent in the x-branch channel at 6:15 am on April 2, 2019

**Comment by JulianUO** [comment]
This is fixed in the debug/nightly builds over discord.
Closing it as the commit comes soon.
