### ISSUE TITLE
Small typo in CCharSpell.cpp makes Followers conflict.

### ISSUE THREAD

**Issue by JulianUO** [Sphereserver/Source-experimental#264]
Here's the typo.
https://github.com/Sphereserver/Source-experimental/blob/0288607533f1653264f38fd0f2688c907d9ff624/src/game/chars/CCharSpell.cpp#L352

It should be:
`if ( !FollowersUpdate(pChar, (maximum(1, iFollowerSlots)), true ) )`

**Comment by JulianUO** [comment]
While we're at it.
This line also:

https://github.com/Sphereserver/Source-experimental/blob/0288607533f1653264f38fd0f2688c907d9ff624/src/game/chars/CCharNPCPet.cpp#L593

To this:
`pOwner->FollowersUpdate(this, -(maximum(1, iFollowerSlots)));`

**Comment by cbnolok** [comment]
Can you explain better which kind of conflict are you referring to? The code should be fine even without those brackets, since they are automatically placed by the macros
```
#define minimum(x,y)		((x)<(y)?(x):(y))
#define maximum(x,y)		((x)>(y)?(x):(y))
```

**Comment by JulianUO** [comment]
In the first typo, the last argument isn't sent to FollowersUpdate, so it won't be triggered as a CheckOnly, and will sum up a follower every time you cast (even when it is not created).
In the second one, when you dispel a creature, you sum a follower instead of removing one, putting the - outside the bracket fixed it.

**Comment by cbnolok** [comment]
Oh you're right, i didn't even know that the `, true` in the if was valid syntax
