### ISSUE TITLE
clilocs showing in tooltips are broken

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#272]
just broken in latest builds

ON=@CLIENTTOOLTIP
ADDCLILOC 3010080, <LEVEL>
Showing now: Level ~1_val~

same problem for items and chars...

it was fine in #3081

**Comment by AtillaG1** [comment]
confirmed, dead bodies, bags, backpacks and all of that stuff is without container count behind name.

**Comment by AtillaG1** [comment]
looks like nay 
![image](https://user-images.githubusercontent.com/25097484/58953927-0f1f5080-8798-11e9-986b-284af523c2a1.png)

**Comment by cbnolok** [comment]
Can't understand the problem

Il mer 5 giu 2019, 13:44 AtillaG1 <notifications@github.com> ha scritto:

**Comment by Seokotov** [comment]
now it looks like
![p1](https://user-images.githubusercontent.com/28328535/58955977-f4ec6f00-87a5-11e9-906f-2f508e61f278.jpg)

**Comment by cbnolok** [comment]
With what code?

Il mer 5 giu 2019, 14:24 Seokotov <notifications@github.com> ha scritto:

**Comment by Seokotov** [comment]
in 3081 it's fine
![p1](https://user-images.githubusercontent.com/28328535/58956109-3c72fb00-87a6-11e9-9924-f04852bd3e65.jpg)
`ADDCLILOC 1063491,<DEF.HTML_WHITETEXT>,<NAME>`

**Comment by cbnolok** [comment]
It looks like is a custom tooltip... It would be useful to know what's the text for that cliloc number, and where are you placing that ADDCLILOC call, like in an itemdef? An event? Under @ClientTooltip or @ItemClientTooltip? Are you RETURNing 1 at the end of that trigger? It's difficult to know what's that about with partial informations

**Comment by Seokotov** [comment]
using it in TYPEDEF 
in trigger @ClientTooltip
ADDCLILOC 1063491,<DEF.HTML_WHITETEXT>,<NAME>

cliloc cell: ~1_val~~2_val~

**Comment by cbnolok** [comment]
@Atilla, here it looks to be working fine. Are you using custom tooltips and returning 1 or is the default tooltip generated by sphere that isn't working for you?
@Seokotov Have you tried with latest commit? Btw i'm pushing another commit that may have fixed that, in case. I'm trying with ADDCLILOC 1060847,<DEF.BFONT_WHITE>,<NAME>

**Comment by Seokotov** [comment]
yes, it's my problem is solved
