### ISSUE TITLE
Z level problems

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#273]
Hi, found potencially some problems with Z levels.
All was working fine on build Compiled at Feb 27 2019 (12:06:15) [build 3046 / GIT hash ded844b40a730f3e8173e7d7bbf0e0416f34fd72] (little older)

**this is basement z=0, watch stone wall on West, this one is making block on pic. 2 (height of wall is z15 (next floor above basement is on level z20**
https://i.gyazo.com/9d1489a0346ddb164d8a693036d725ae.png

**This picture is on same tile as wall from picture 1, player cant make step through that tile, even it has to be 5levels above wall...**
https://i.gyazo.com/ff1fba1e44f146e3a1d048a1085291c0.png

_**From basement z0, i put i_paver_stone here, and edit it to z15, if i move myself on that stone paver, it automaticaly teleport me on z20 ---> its little bit weird to explain :D , feels to me it is missing some levels, or some base z offset is little bit moved up or down...**_

It is for both, static houses or multi houses. For some reason, 20 height difference is not enough for second house layer, even walls are 15?. :O 
edit: if i put stone pavers on z level +21 above that wall tile, i can walk through that tile.

**Comment by AtillaG1** [comment]
So walls are maybe 20height, so that means, you are blocked to walk through wall on z20, you must be on z21. It has to be bug. Same problem then is if you want to go through doorway, it is counting my height +1 bug.

**Comment by AtillaG1** [comment]
5196,3993,37;  5290,3983,37;  5289,4007,40 you can try here --- this is only one part of problem

**Comment by Seokotov** [comment]
> 5196,3993,37; 5290,3983,37; 5289,4007,40 you can try here --- this is only one part of problem

work fine for me

**Comment by AtillaG1** [comment]
As a GM char i can go through too. 
We didnt change anything in statics or map in like 2 years so... Something has to be different in sphere. :(

**Comment by Seokotov** [comment]
height_0190 12 //DEFNAME=c_man
height_0191 12 //DEFNAME=c_woman
height_0192 10 //DEFNAME=c_ghost_man
height_0193 10 //DEFNAME=c_ghost_woman

in sphere_defs
yes, remember about this bug. it was 2-3 month ago

**Comment by AtillaG1** [comment]
height_0190 16 //DEFNAME=c_man
height_0191 16 //DEFNAME=c_woman
height_0192 16 //DEFNAME=c_ghost_man
height_0193 16 //DEFNAME=c_ghost_woman

mmm we have much more. Question is what now :D change it in defs, or wait :O

**Comment by AtillaG1** [comment]
fixed in last.

**Comment by AtillaG1** [comment]
after last commit, the problems with Z in some places are back :(
![image](https://user-images.githubusercontent.com/25097484/58954565-d41e1c80-8799-11e9-8e97-8f8b38d7b6a0.png)
cant move to West

**Comment by cbnolok** [comment]
With your map files, if you go on the carpet (which is placed at z=11 instead of z=10, dunno why), the height difference between you and the floor above would be 19. As you know, a mounted c_man has a default height of 16+4, so you would need 20 as the minimum height difference to be able to step below that (if you are using If you have EF_WalkCheckHeightMounted).

**Comment by AtillaG1** [comment]
hm.
