### ISSUE TITLE
Can try to pickup dead body

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#274]
The problem is here again.
Players can try to pickup dead body of monsters, npcs and players, Most likely after that try, their game crash.

:(((

**Comment by cbnolok** [comment]
Which client? I may be wrong but i remember this started with a specific client version and i fear sphere can't do much to prevent the pick up request from being sent by the client

**Comment by AtillaG1** [comment]
7.0.29.2 - most likely client crash
7.0.35.6 - same
only some external apps can little bit help, that your game not crashing that much.

I think it was fixed some time ago if im not wrong ?

**Comment by AtillaG1** [comment]
5196,3993,37;  5290,3983,37;  5289,4007,40 you can try here

**Comment by Seokotov** [comment]
yes, sometime it's happen now
body of monster can change position after you try to pick it up
using 7020

**Comment by cbnolok** [comment]
It was fixed by making sphere refuse the client's pickup request, can you check if it works with older clients instead? It should be the client in first instance to not be sending the packet, and if it's sent, we can't do much more than sending a pickup request deny packet i fear (like we are already doing)

**Comment by Seokotov** [comment]
yeah it  was fixed for 7020 client too...but now it happen again

**Comment by cbnolok** [comment]
The fix wasn't client-version specific, if with the same sphere version 7020 doesn't crash but later versions do, then ea broke even more the new clients

**Comment by AtillaG1** [comment]
So whats the best way to go now ? We didnt change client for 5 years, once it was not doing, then yes, again not, now it is again and mostly it is crashin also...
Is there some way to do a fix for ourself somehow ?:-D

**Comment by AtillaG1** [comment]
Now client 7020 isnt able to try to pickup body as a player char.
7.0.29.2 - still trying to pick it up :(

**Comment by Seokotov** [comment]
im still can pick up corpses of monsters by player char...
have no any messages or crashes...just flip it
3106 build 7020 client

**Comment by AtillaG1** [comment]
can i close it here ?

**Comment by AtillaG1** [comment]
probably looks fixed.
