### ISSUE TITLE
Many criticals, undefined reason

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#276]
So we placed big boat on water, then we enter this boat with GM chars. Then i deleted it.
Since this, my buddy does nothing and console is spammed with these things. Also he cant log in anymore, everything he does will pops out another critical. Even attempt to delete his char will shows up some critical.

https://pastebin.com/qpDbPEXw

dont know more informations, im literally sad because i feel like we are going in circles for one year now. :( FeelsBadMan

**Comment by AtillaG1** [comment]
Also his character is still seeable in game, even he is logout. Will se when he disappear.

**Comment by cbnolok** [comment]
Here it's all fine, can you test with clean scripts and most importantly a clean uo setup?
