### ISSUE TITLE
Placing house, boat

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#277]
After every placing.

08:46:ERROR:Undefined symbol '' ['ei_house_component']
08:46:ERROR:Unknown 'EVENTS' Resource 'ei_house_component'
08:46:ERROR:Undefined symbol '' ['ei_house_component']
08:46:ERROR:Unknown 'EVENTS' Resource 'ei_house_component'
08:46:ERROR:Undefined symbol '' ['ei_house_component']
08:46:ERROR:Unknown 'EVENTS' Resource 'ei_house_component'
08:46:ERROR:Undefined symbol '' ['ei_house_component']
08:46:ERROR:Unknown 'EVENTS' Resource 'ei_house_component'

not from our scripts at all.

**Comment by cbnolok** [comment]
That event is added by sphere and you have at least to define it in your
scripts. It's in the changelog

Il ven 7 giu 2019, 08:50 AtillaG1 <notifications@github.com> ha scritto:

**Comment by AtillaG1** [comment]
ty
