### ISSUE TITLE
UserExtCmd 255 not work

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-experimental#280]
on=@UserExtCmd
if (<argn1>=255) // it not work
serv.log work
endif

**Comment by Leodinas** [comment]
not fix

**Comment by cbnolok** [comment]
As we talked on discord, have you first verified that your custom packet
length does not exceed 40 bytes?

Il sab 13 lug 2019, 16:39 Breaker <notifications@github.com> ha scritto:

**Comment by Leodinas** [comment]
okay  fix
