### ISSUE TITLE
Critical exceptions

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#282]
The player unlocked metal chest, then started to moving some items and lock it again. This errors comes out heavily, also his client once crashe meanwhile.
never saw that before.
https://pastebin.com/zCPU2EZY

**Comment by cbnolok** [comment]
Is it still happening? I couldn't figure out yet the cause, in any case i added some more checks, so that the call stack can be more accurate.

**Comment by AtillaG1** [comment]
Not happening right now, but also im not using latests anymore.
It should be because of problems with our reeeealy old server HW, there were mooore errors.

But we got new HW and server so i think i can close it for now.
