### ISSUE TITLE
Critical

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#290]
crashed sphere.
https://pastebin.com/jSpK0fix

**Comment by cbnolok** [comment]
Did it happen with a recent build or with an old one?

**Comment by AtillaG1** [comment]
with latest one.
(not todays one)

**Comment by cbnolok** [comment]
Can you check if something similar is still happening with the current version?

**Comment by AtillaG1** [comment]
not happened yet since last time.

**Comment by AtillaG1** [comment]
reopened, today crashed
https://pastebin.com/wDbkhWkt

**Comment by AtillaG1** [comment]
I think on latest everything it does now is warning: undefined definition, instead of crash. So it looks good.
