### ISSUE TITLE
Debug sphere spam

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#291]
pretty good spam with cca 10 people ON.
https://pastebin.com/qVvP3Zwk
CombatFlags=00020|00100|00040
[3:37] Atilla: // COMBAT_DCLICKSELF_UNMOUNTS   00020  // Unmount horse when dclicking self while in warmode
// COMBAT_ALLOWHITFROMSHIP      00040  // Allow attacking opponents from ships
// COMBAT_ARCHERYCANMOVE        00100

**Comment by cbnolok** [comment]
Guess you have custom combat events, right?

**Comment by AtillaG1** [comment]
yes we have. whole combat system

**Comment by cbnolok** [comment]
It should be fixed

**Comment by AtillaG1** [comment]
Before i close it, we noticed many monsters are dumb, that they said they are attackign someone, but then they are instantly wandering, not attacking at all.

Should be something with connection with this issue ?
The spam should be good, didnt tested with more players, but we will see in future. Its kinda harder to run debug on live shard where players already playing.

**Comment by cbnolok** [comment]
Can you check with default scripts first? I suspect it may be your combat system, but i'm not 100% sure

**Comment by AtillaG1** [comment]
About debug spam, for now it looks fixed, will see another day when we are able run debuger longer than to next save without problems.
About our combat, we are still using basic brains, maybe some NPCs have some enchanted brain, but there is nothing that is changing their ability to attack or somethign like that. But im also not 100% sure because everything is weird and we did lot of changes in same time while moving to X1.
