### ISSUE TITLE
Sphere random shutdowns

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#293]
On the latest commit, our sphere is crashing randomly 2-3x / per night-day.
There is no error in log or anywhere.

We are not sure if its sphere problem or not, right now we are trying to find out, but it is little bit tricky, without errors or anything.

Build before latest was fine, as far as i know.

**Comment by cbnolok** [comment]
Have you tried with the debug build attached to the debugger?

**Comment by AtillaG1** [comment]
I would love to, but i forgot how to set it up :(
i have it working on my personal PC, but we already moved on live server.

**Comment by AtillaG1** [comment]
OK GOT IT!!!
Everytime you want to buy something from nPC or vendor, and you didnt write command correctly, it will shutdown.
I came to mage, said xxbuy and it crashed.

**Comment by AtillaG1** [comment]
Even if you goes like [Name] buy, the vendor dont recognize his name and it will crash too.

**Comment by AtillaG1** [comment]
fixed, ty!
