### ISSUE TITLE
Sphereaccu now DEC ?

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#294]
In latest commit, all our tags in sphereaccu are in DEC instead of HEX as in previous build.

It made some problems with linked items, no one cant equip anything linked to him now :(
I mean the fix by ourself would be easy i guess, but is it ok ?

TY.

**Comment by cbnolok** [comment]
The tags were saved as a hex value by accident recently, historically they were always saved as a decimal number (if the tag is pure numeric and not treated as a string)

**Comment by AtillaG1** [comment]
OK no prob then, i think we can fix it by one eval or something.
