### ISSUE TITLE
Something is potentially cycling ?

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#299]
Hi i just dont want to straightly report it as an issue, but we have some huge performance problems with sphere and yet we didnt found why. It is finally on our LIVE server.

I jsut want to collaborate or ask for any informations from your experiences...

After start, sphere is running awesome for i would say like, 10 hours minimally and more, but after for example 15 or 20 hours, the sphere start lagging pretty badly. Only restart sphere will help again for same time cycle.

The lags are in weird intervals, intervals are more and more frequent. For example 20seconds OK, then huge lag for 1-2s, then again 20 seconds nothing and again lag.
Then it is 10 seconds OK, and lag. At the end of the cycle when restart is needed, it is lagging like 5s OK and then lag.

What should we do ? We tried to stop every HC script, check if anything is cycling, check some console dumps to check but nothing special to say told whats wrong.

Thank you for any idea or suggestion.

**Comment by cbnolok** [comment]
Any clue with the profiler?

**Comment by cbnolok** [comment]
Closing, since after some tests it was more a script problem than a sphere one (even if some optimization on sphere side, regarding script parsing, is needed).
