### ISSUE TITLE
Items disappear after you pick'em

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#300]
Sometimes there is something wrong with picking up items from ground. 
Problem I. : you try to pick up item from ground and then it will diseapper in your hand. After .resync is on the ground again. Sometimes it happen multipletimes before you are able to finally pick him up.

Problem II. : sometimes you try to pick that item, he diseapper from hand and also from server. It is no more there even after .resync.

**Comment by cbnolok** [comment]
Are you using a third party client? Can it happen with every item or only
specific types or attr? Tried with default scripts before?

Il lun 22 lug 2019, 18:35 AtillaG1 <notifications@github.com> ha scritto:

**Comment by AtillaG1** [comment]
Ok so its happening only when you are out of reach from every item. You can pick it up, no more sphere msg like "you cant pick it up" or something.
With default scps it is same, even worst because there isnt .resync workign for me :D

**Comment by AtillaG1** [comment]
client 7.0.35.0
every item not matter what

**Comment by AtillaG1** [comment]
fixed, ty!
