### ISSUE TITLE
Monsters dont fight

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#302]
Just made new topic for it.
Not every monsters arent attacking, some are OK.
Should be not problem with our dmg system, monsters with default brains arent attacking too.

https://i.gyazo.com/910e2262ae63589ae06952d21f5980e4.gif

**Comment by cbnolok** [comment]
To be sure, have you tested with default scripts?

**Comment by AtillaG1** [comment]
Tested it now with some basic monsters and most of them are attacking back when i hit them. Not every monster attack you first by themselfs.

**Comment by AtillaG1** [comment]
Well looks like finally found out what scripts is doing it. Closing for now.
