### ISSUE TITLE
attacker elapsed long timer

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#304]
```
[function f_logout_test]
serv.log funkcia start
if (<attacker> > 0)
local.x=0
for <attacker>
serv.log elapsed: <attacker.<eval <local.x>>.elapsed>
if (<attacker.<eval <local.x>>.elapsed> < <argv[0]>)
local.resolution=1
endif
local.x +=1
endfor
endif
return <eval <local.resolution>>
```

https://pastebin.com/9v28e98n
the step should be every second, and the test script should end on elapsed = 3 (which should be around 3s, but instead it is like 20s)

**Comment by cbnolok** [comment]
I can't understand the purpose of this script, it will always return 0 or 1, and will simply log the elapsed value for each attacker.

**Comment by AtillaG1** [comment]
yes it has to do it like that, but in 1s each, now it is doing like 5s....

`on @timer
if (<cont.attacker.target>) && (<cont.attacker.target>!=04fffffff)
if <cont.attacker.last.elapsed> < 180
cont.say Kal Xen An Flam
cont.anim 17
timerf 2,cont.rockdung_elementalsummon
timer={10 24}
return 1
endif
endif
timer=5
return 1`

this script has to check time after last attack on him/hit, then after 180s stop casting summon.
Now the 180s of this check is gonna be like 700s because it is somehow slowed down.

> attacker.last.elapsed
> You will see the length of time since the first opponent has damaged output to the console.
