### ISSUE TITLE
Frequent sphere crash in same interval

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#306]
Hi,
in interval of 1-2 days, the sphere will randomly crash without any informations given.
Only one think that is shown  sometimes before random crash is this.
Unfortunately, there is nothing more to give u as help info, console shows nothing.

Edit: Just find out that before every crash, there was this error i shown to you no longer than 5 minutes before crash.

```
20:11:WARNING:77:Client crashed. Account: 'Dex'. Data from Crash Report packet:
20:11:WARNING:P=0,0,0,0, ErrorCode=0xC0000005, Description='CRASH', Offset=0x243C65CE, ClientExe='', ClientVer=7.0.35.6
20:11:WARNING:Char attached. Last server P=5996,93,0,0
```

**Comment by roberpot** [comment]
Try to execute it with GDB or activate the cores and get us the back trace.

**Comment by AtillaG1** [comment]
mmm, dont know what both of these means. Also how to activate or execute them.
Maybe i know it with different name :O

**Comment by cbnolok** [comment]
He's using sphere on windows, the equivalent would be running the debug
version with the debugger and waiting for the crash

Il lun 29 lug 2019, 10:27 AtillaG1 <notifications@github.com> ha scritto:

**Comment by AtillaG1** [comment]
Ok thats better, will try it. Ty.

**Comment by AtillaG1** [comment]
![image](https://user-images.githubusercontent.com/25097484/62081039-16bc1c80-b252-11e9-8e2a-0617746946f9.png)
first stoppage
looks like cant get through...

**Comment by AtillaG1** [comment]
today it crashed again and nothing suspicious to see from logs. Will run debugs again and will see.

**Comment by AtillaG1** [comment]
https://pastebin.com/0swj7Uu0 dropped twice in 2 hours, last thing from me :D

**Comment by cbnolok** [comment]
Closing it, since we couldn't find the source of the crash and i don't know if this is still happening (plus, i fixed some code which could generate exceptions or crashes). Feel free to reopen this if there are news.
