### ISSUE TITLE
Only your gold limits how much vendors can train you to

### ISSUE THREAD

**Issue by Iron-Wolf-UO** [Sphereserver/Source-experimental#307]
Even after deleting the e_trainer event from vendors, vendors can still train you to unlimited hights, only gold is the limit.
You can go well above 1000, 2000 or 3000% skill. - Fault is both in click menu and spoken "train"

**Comment by Iron-Wolf-UO** [comment]
Please note if you have below (whatever "train up to max" you have set in sphere.ini) it works, they only offer you to train to that, but then as soon as you are above (lets say 30.0) you can go and talk to them again, and then they will give you 1 skill pr. 1 gold, for as long as you have gold

**Comment by cbnolok** [comment]
Have you tried with the default scriptpack? I can't replicate here

**Comment by Iron-Wolf-UO** [comment]
Thats wierd, i have no scripts interferring with vendors, but if you cant recreate it, i apologize for the waste of time, i will do some further investigation on my end. Thought maybe there was something hardcoded with this new: @PayGold ... because as soon as i have surpassed the limited 30.0 skill, i can just drop gold on them and they train directly scaled with the gold i drop.. aint no limit, can go well above 100.0 skill - But thanks for the testing

**Comment by cbnolok** [comment]
No problem, feel free to reopen this issue if you find it isn't script related!
