### ISSUE TITLE
human NPC's equipping shield/weapon

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#309]
NPCS is equipping either weapon and shield, or bow/crossbow.
The problem is in moment where npcs has shield and bow/crossbow.
They are just trying to equip it all the time ---> or atleast in backpack it is still changing positions.
If you have shield and dagger ---> then it is ok and it is not trying to equip some weapon still.
We found out because our main boss hass bow and shield and he is switching depends on distance of players, but now he is just trying to equip bow still.

Kinda hard to explain 🗡 

[![Screenshot from Gyazo](https://gyazo.com/93b75dd47761aecac2352d7b170a52a5/raw)](https://gyazo.com/93b75dd47761aecac2352d7b170a52a5)
[![Screenshot from Gyazo](https://gyazo.com/69d7e1bf61081e2910d57691ac37e2d0/raw)](https://gyazo.com/69d7e1bf61081e2910d57691ac37e2d0)

**Comment by cbnolok** [comment]
Have you tried disabling mt_usehands? I can't remember if that makes the
npc not to use weapons at all though

Il sab 3 ago 2019, 00:47 AtillaG1 <notifications@github.com> ha scritto:

**Comment by AtillaG1** [comment]
NPC_AI_EXTRA in sphere. ini fixed problem.
