### ISSUE TITLE
sphere crash

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#319]
https://pastebin.com/bsC4Qf4w

**Comment by cbnolok** [comment]
It looks like a script enters an endless loop, maybe after an item is
dclicked, can you investigate further?

Il mer 21 ago 2019, 14:44 AtillaG1 <notifications@github.com> ha scritto:

**Comment by AtillaG1** [comment]
deeds arent working to unpack, somethjing like bellow.

> [ITEMDEF I_DEED_FORGE]
> NAME=Deed to a Forge
> ID=i_deed
> RESOURCES=30 i_building_stone,10 i_log, 10 i_ingot_iron
> SKILLMAKE=BLACKSMITHING 60.0,TINKERING 40.0,MINING 50.0
> CATEGORY=Provisions - Deeds
> SUBSECTION=Item Deeds
> DESCRIPTION=Forge
> 
> ON=@Create
>     MORE=i_forge

**Comment by cbnolok** [comment]
I don't think so, i suppose you need to identify the item which, after being doubleclicked, makes sphere hang and crash.
