### ISSUE TITLE
custom housing (not placing multi but items)

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#320]
it will place item 7605 (0x1DB5) instead of multi 7605 .
![image](https://user-images.githubusercontent.com/25097484/63470381-d32d8a80-c46c-11e9-820f-c70c963e9cd1.png)

**Comment by cbnolok** [comment]
It looks to me that it's working:
![immagine](https://user-images.githubusercontent.com/15048996/63508942-4d94f380-c4db-11e9-98d9-aa784ef78017.png)

7605 multi is the stair at the left, and i added that one in the house customizer. Am i missing something?

**Comment by AtillaG1** [comment]
Hmmm interesting. It is OK even after commit of these multis ?

**Comment by cbnolok** [comment]
Yup, my guess is that you have different/invalid stairs.txt on the server, client or both.

**Comment by AtillaG1** [comment]
ok so it will place stairs correctly, but after commit, it will print error "you have something wrong somewhere and you cant commit" and then it will change to that item.
The stairs.txt are same only some additional graphics......
Client 7.0.35.0

**Comment by cbnolok** [comment]
Can you test with a vanilla client and also on 56c/d, for both the problems? I don't have the console error here, and i want to be 100% sure that is sphere's fault before messing with that complex code (also, i never had used the house customization).

**Comment by AtillaG1** [comment]
with X latest and X scripts it is working. With our scripts NOT.
with coruja latest build and his scps = working. With our scripts working.
