### ISSUE TITLE
EF_ItemStacking and itemdropon_item

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#322]
EF_ItemStacking enabled in sphere.ini, if you try to drop item on the other item (@itemdropon_item) and are you doing it if you are bellow z=0, the dropping item will be set on z=1 always.

If you disable this setting, it works OK and even stacking looks working.
edit: everywhere when you are bellow z=0 it will place item on z=1 // on Ilshenar even above z=0

**Comment by soulless320** [comment]
Can confirm this problem, itll pop it to z 1 if you are below.

**Comment by AtillaG1** [comment]
working.
