### ISSUE TITLE
Webserver / Homepage

### ISSUE THREAD

**Issue by Iron-Wolf-UO** [Sphereserver/Source-experimental#324]
Still some issues, mainly seedlength exceeding maxlength of 127 (Disconnecting)
Also the .ini does not reflect .html, only .htm

![Udklip](https://user-images.githubusercontent.com/53218493/64636329-c19f2900-d401-11e9-8f7f-9a67e26a5fae.PNG)

**Comment by cbnolok** [comment]
Can't replicate the seed length error, nor the .html one. Though, i noticed that in some cases a blank webpage is sent, i'm sending a commit for that right now.
