### ISSUE TITLE
Muti/custom building drop items

### ISSUE THREAD

**Issue by Mudraon** [Sphereserver/Source-experimental#328]
If we have a multi-floor house and we try to put the item on the upper floor and the wall is in line on the lower floor, the item will return to the backpack
https://ctrlv.tv/LaaA

**Comment by Swiftik023** [comment]
and when I'm under wall and my (weight + item weight) > maxweight -> item go to map cord 0,0 with msg_heavy

**Comment by Mudraon** [comment]
It's working!
