### ISSUE TITLE
"Z" teleport not work properly

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-experimental#331]
hi, watch this.

```
[function gmtele]
targetfg f_gmtele

[function f_gmtele]
go=<targp>
```

When I have .gm and I target wall in Z=20 I go to Z=0
https://gyazo.com/980791759a36fad50760f2cd83dfe281
without .gm it's ok
https://gyazo.com/67716b0706571d687cde3cb6cf2277f5

**Comment by cbnolok** [comment]
Can't replicate it here, are you sure you have the same map and statics files between client and sphere? If it's not the problem, could you find a spot in a default map where you can get this bug?

**Comment by AtillaG1** [comment]
Moonglow 4455,1072
https://gyazo.com/da1324b276084d5235f716c1b6431914
https://gyazo.com/a0dda7c2a950ce7da02ecf9e9bbc15ea

**Comment by Swiftik023** [comment]
solved
