### ISSUE TITLE
exception generated while executing region triggers

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#335]
exception generated while executing region triggers
it's happen rarely but...
![p2](https://user-images.githubusercontent.com/28328535/67716095-30e5d200-f9dc-11e9-8f47-7ded9c664fc4.jpg)

**Comment by cbnolok** [comment]
You have an outdated version, probably of a couple of months. This kind of support is only for current versions. Feel free to reopen the issue and paste a new stack trace if you have this again with latest version.
