### ISSUE TITLE
Teleporters created from custom houses do not work

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-experimental#336]
They teleport you to the center of the structure at ground level and you get stuck. I tried this with GM on and GM off, same results. 

![image](https://user-images.githubusercontent.com/17236327/67919432-a71e3c00-fb76-11e9-9bbb-a7b0b126c85f.png)

**Comment by cbnolok** [comment]
Exactly how are you creating those teleports?

**Comment by soulless320** [comment]
Just adding them from the custom house menu 
![image](https://user-images.githubusercontent.com/17236327/69109896-0faa5b80-0a47-11ea-8cea-ae172651ea98.png)

**Comment by soulless320** [comment]
Fixed, thank you!

also for anyone who wants it to work exactly like OSI
```[typedef ei_house_telepad]
//this is handled in the telepad typedef

on=@step
if !(<argn1>)
  type=t_script		
  sound 01f0
  src.timerf 1,f_house_telepad_go,<uid>
endif

[function f_house_telepad_go]
ref1=<args>
if (<distance <ref1>> < 1)	//standing on it
  go=<ref1.morep>
  effect=3,i_fx_smoke,6,30,0
  sound 01ef
endif```
