### ISSUE TITLE
gate travel color not work again

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#337]
The moongate generated by the Gate Travel spell at the destination P had a color which didn't match the destination region safe/unsafeness
looks like it was a problem #283

**Comment by cbnolok** [comment]
Here it works, are you sure you have a blank EFFECT_ID under that spell?

**Comment by Seokotov** [comment]
> Here it works, are you sure you have a blank EFFECT_ID under that spell?

EFFECT_ID=i_moongate_blue

it's always blue

**Comment by cbnolok** [comment]
Yes you need to remove i_moongate_blue, otherwise you force that id always

Il lun 4 nov 2019, 02:20 Seokotov <notifications@github.com> ha scritto:

**Comment by Seokotov** [comment]
like in scriptpack
anyway, i removed it but it still always blue

**Comment by cbnolok** [comment]
Are you sure that the areas are unguarded? I tested inside and outside a
guarded region and it worked

Il lun 4 nov 2019, 16:51 Seokotov <notifications@github.com> ha scritto:

**Comment by Seokotov** [comment]
yes im tested it
now i just restart sphere and moongate always red :)

**Comment by cbnolok** [comment]
Which are the flags of both origin and destination regions?

Il lun 4 nov 2019, 17:04 Seokotov <notifications@github.com> ha scritto:

**Comment by Seokotov** [comment]
ahh now looks like work...strange
i'll test it more now

**Comment by Seokotov** [comment]
looks like ok now
