### ISSUE TITLE
You are not privileged to do that

### ISSUE THREAD

**Issue by Swiftik023** [Sphereserver/Source-experimental#339]
On build from Nov 3rd, 2019 is problem with Counselor (plevel 2) and Seer (plevel 3) privileges. Every command report msg_acc_priv (You are not privileged to do that) 

in the previous build it was okay

edit: only .info and player (plevel 1) commands it's ok

**Comment by cbnolok** [comment]
Seems to work fine here, are you sure you haven't changed your spheretables?

**Comment by Swiftik023** [comment]
on the last version it looks ok
