### ISSUE TITLE
Guards don't do instakill.

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source-experimental#34]
Even when the setting is enabled, it sets the target hits to 1.
Softcoded fix:

ON=@Hit
ARGN1=2000

**Comment by azmanomer** [comment]
actually they are oneshotting for me they are hitting like 10k.

**Comment by cbnolok** [comment]
It works here, calling the guards on both a plevel 1 client and a plevel 7 (gm off) client kills the criminal with both GuardsInstantKill = 1 and 0.

**Comment by nefthon** [comment]
Guards are doing 20000 damage hardcoded, but take in count that they are normal NPCs in terms of global events, so any Combat Event modifying damage dealt will affect them too so an exception must be made for them to make normal damage either on the combat system or in their chardef or guard's custom event.

**Comment by cbnolok** [comment]
Closing it, since it seems to be a script problem. Feel free to reopen it if otherwise.
