### ISSUE TITLE
players can use items from bankbox even if it closed and far away

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#344]
players can use items from bankbox

looks like 
// EF_FixCanSeeInClosedConts    00020000 // Change CANSEE to return 0 for items inside containers that a client hasn't opened
not work
or it's another bank bug?

**Comment by soulless320** [comment]
Could not replicate this, more information needed.

**Comment by Swiftik023** [comment]
set macro equip shield and shield insert to bankbox, close bankbox and use macro. Shield will be equiped

**Comment by Seokotov** [comment]
all players can use any items from bankbox via macro
even can use shovel that still in bankbox for dig

**Comment by Seokotov** [comment]
fixed
