### ISSUE TITLE
Mount removed in GC after DISMOUNT in combat

### ISSUE THREAD

**Issue by Seokotov** [Sphereserver/Source-experimental#347]
Player was dismounted in combat by function DISMOUNT
He mounted back and log out

But GC just removed horse with error 
`21:57:Garbage Collection: started.
21:57:ERROR:UID=042a3, id=0b1 'dread warhorse', Fixed mount item UID=040008fc0, id=043f3 'dread warhorse'`
it's happen sometime

so something wrong with dismount or GC

**Comment by cbnolok** [comment]
To me it looks like you're somehow messing with mount items or something like that, since i haven't hears something like that from anyone else and i can't reproduce it. In any case i added a lot of warning/error messages that will help in finding at which level is the problem
