### ISSUE TITLE
DEBUG messages when player got killed

### ISSUE THREAD

**Issue by shiryux** [Sphereserver/Source-experimental#37]
15:26:P'Azuleta' was killed by N'skeleton'
15:26:DEBUG:Printing STACK TRACE for debugging.
15:26:DEBUG:__ thread (3680) _ |  # | _____________ function _____________ | ticks passed from previous function start
15:26:DEBUG:>>         3680    |  0 |                       CWorld::OnTick | +0 
15:26:DEBUG:>>         3680    |  1 |                      CSector::OnTick | +0 
15:26:DEBUG:>>         3680    |  2 |                        CChar::OnTick | +0 <-- exception catch point (below is guessed and could be incorrect!)
15:26:DEBUG:>>         3680    |  3 |                         CChar::Death | +0 
15:26:DEBUG:>>         3680    |  4 |                      CChar::LayerAdd | +31 
15:26:DEBUG:>>         3680    |  5 |                        CItem::Update | +0 
15:26:DEBUG:>>         3680    |  6 |                      CClient::CanSee | +0 
15:26:DEBUG:>>         3680    |  7 |                        CChar::CanSee | +0 
15:26:DEBUG:>>         3680    |  8 |             CPointBase::GetDistSight | +0 
15:26:CRITICAL:Error Pri=2, Code=0xc0000005, Desc='Exception', in CChar::Tick() #1 "death"

**Comment by cbnolok** [comment]
This shouldn't happen anymore with most recent builds. There wasn't any  fix targeting this specific issue, but more wide ones which most probably have solved also this problem. I'm closing, but of course reopen if occurring again
