### ISSUE TITLE
Criminal issue

### ISSUE THREAD

**Issue by azmanomer** [Sphereserver/Source-experimental#40]
Player A and player B is blue. A hit B. A become criminal only for B.   A and B have memory_irritatedby,memory_sawcrime,memory_harmedby but even i remove all of them A still criminal to B. I think B should have memory_aggreived but he doesnt.

**Comment by jkachhad** [comment]
Removing the memory items does not correct the issues because notoflags are saved/cached. 
To fix the issue, I think A checkcrimeseen needs to be implement on OnHarmedBy.

**Comment by cbnolok** [comment]
Have you tried to do NOTOUPDATE after you remove the memories?

**Comment by azmanomer** [comment]
yeah after use NOTOUPDATE its working :) so should i add that memory to player A to make him criminal for player B manually if i want to make him crim only for player B and NOTOUPDATE right?

**Comment by cbnolok** [comment]
That's the important code:
```
if (this != pCharViewer) // Am I checking myself?
{
	// If they saw me commit a crime or I am their aggressor then criminal to just them.
	CItemMemory * pMemory = pCharViewer->Memory_FindObjTypes(this, MEMORY_SAWCRIME | MEMORY_AGGREIVED);
	if (pMemory != NULL)
		return NOTO_CRIMINAL;
}
```
You can choose to add a MEMORY_SAWCRIME or a MEMORY_AGGREIVED to the char that should see someone as a criminal, and link the memory to the criminal. Then you need to do NOTOUPDATE.

**Comment by azmanomer** [comment]
thx for answer i think we can close the issue.
