### ISSUE TITLE
[PORT] 1fa0504b39e9df1074fb29121da2446926eb56b6,Changed: Max item capacity on containers changed from 255 to 125

### ISSUE THREAD

**Issue by nefthon** [Sphereserver/Source-experimental#60]
Revision: https://github.com/Sphereserver/Source/commit/1fa0504b39e9df1074fb29121da2446926eb56b6
Author: Coruja coruja@outlook.com
Date: 03/08/2016 08:59:17
Message:
Changed: Max item capacity on containers changed from 255 to 125
This is required to make containers works properly on Enhanced Clients, because containers on these clients have hardcoded capacity of 125 items (OSI already uses this value since many years ago, even before enhanced client)

**Comment by cbnolok** [comment]
Added and improved in commit 17ee3ce8676e802fa0a3586634a6e58f07e576d3.
