### ISSUE TITLE
[PORT]6e0f90f61fdd81d522143e35b6d968137c3d39ab, Fixed: Client encryption not being decrypted correctly on login process

### ISSUE THREAD

**Issue by nefthon** [Sphereserver/Source-experimental#71]
To be tested more and eventually ported.
Revision: https://github.com/Sphereserver/Source/commit/6e0f90f61fdd81d522143e35b6d968137c3d39ab
Author: Coruja coruja@outlook.com
Date: 25/01/2017 17:44:31
Message:
Fixed: Client encryption not being decrypted correctly on login process
Also reverted changes on packet 0BF 018 accidentally sent some commits ago

**Comment by cbnolok** [comment]
Fixed and improved in commit 337188576e20fbbd32822f12159ed54ff7113a9b.
