### ISSUE TITLE
War memory problem

### ISSUE THREAD

**Issue by merttumer** [Sphereserver/Source-experimental#77]
Physical attacks give players war memory but casting harmful spells don't. They should also give war memory

**Comment by cbnolok** [comment]
Exactly, which memory? memory_fight?

**Comment by merttumer** [comment]
yes memory_fight sorry

**Comment by merttumer** [comment]
the one you get when you hit another player

**Comment by cbnolok** [comment]
Can you check if the memory is added and/or the offended player responds by attacking if the caster is next to him (0-1 tiles of distance)?

**Comment by cbnolok** [comment]
And is in this case the memory added?

**Comment by cbnolok** [comment]
Is this issue still present?
