### ISSUE TITLE
on=@kill doesnt store npc info

### ISSUE THREAD

**Issue by merttumer** [Sphereserver/Source-experimental#81]
when players have on=@kill trigger and a player kills a npc theres no way to get the npc info. Both argo.uid and src.uid point the players uid. Argo.uid used to show npcs' uid

**Comment by nefthon** [comment]
Fixed on 87cf9724f6cac8d645cb45156b5c59a6c4d5403e:
ON=@Kill is being fired on the killer with SRC set to the death character.
