### ISSUE TITLE
Spawnbit doesnt respawn the npc

### ISSUE THREAD

**Issue by merttumer** [Sphereserver/Source-experimental#82]
Spawnbits' timers are always -1 and doenst respawn the creature. When the timer is set to 1 by command it repawns but then it returns to -1. also if the spawn is activated and timer set to 1, it respawns the new creature and old creature disconnect from the spawnbit

**Comment by nefthon** [comment]
Tho couldn't reproduce some of this problems there was an issue with Spawnbit's timers sometimes set to -1 that was fixed few commits ago, I pushed a commit now with some spawns issues fixed, reply here if there are still problems with them.
