### ISSUE TITLE
foinstances debug error

### ISSUE THREAD

**Issue by merttumer** [Sphereserver/Source-experimental#88]
forinstances i_katana_vanq
serv.log "xx"
endfor

gives debug error

12:57:DEBUG:Printing STACK TRACE for debugging.
12:57:DEBUG:__ thread (19104) _ |  # | ___________ function ___________ | ticks passed from previous function start
12:57:DEBUG:>>         19104    |  0 |      NetworkManager::processAllInput | +0 
12:57:DEBUG:>>         19104    |  1 |           NetworkInput::processInput | +16 
12:57:DEBUG:>>         19104    |  2 |            NetworkInput::processData | +0 
12:57:DEBUG:>>         19104    |  3 |            NetworkInput::processData | +0 
12:57:DEBUG:>>         19104    |  4 |  NetworkInput::processGameClientData | +0 
12:57:DEBUG:>>         19104    |  5 |     PacketSpeakReqUNICODE::onReceive | +0 
12:57:DEBUG:>>         19104    |  6 |           CClient::Event_TalkUNICODE | +0 
12:57:DEBUG:>>         19104    |  7 |               CClient::Event_Command | +0 
12:57:DEBUG:>>         19104    |  8 |                        CChar::r_Verb | +0 
12:57:DEBUG:>>         19104    |  9 |                     CObjBase::r_Verb | +0 
12:57:DEBUG:>>         19104    | 10 |                   CScriptObj::r_Call | +0 
12:57:DEBUG:>>         19104    | 11 |             CScriptObj::OnTriggerRun | +0 
12:57:DEBUG:>>         19104    | 12 |         CScriptObj::OnTriggerForLoop | +0 
12:57:DEBUG:>>         19104    | 13 |             CScriptObj::OnTriggerRun | +0 <-- exception catch point (below is guessed and could be incorrect!)
12:57:DEBUG:>>         19104    | 14 |                  CFile::GetFileTitle | +0 
12:57:DEBUG:>>         19104    | 15 |                CSFile::GetFilesTitle | +0 
12:57:DEBUG:key 'serv.log' runtype '1' pargs '0000009C75FA84EA' ret '' [0000009C75808848]

**Comment by cbnolok** [comment]
Can't reproduce it even with a more complex function like this:
```
[function test1]
serv.log pre katana
forinstances i_katana
local.n ++
serv.log "katana" <dlocal.n>
endfor
serv.log post katana - pre worldgem
forinstances i_worldgem_bit
local.m ++
serv.log "worldgem <dlocal.m>"
endfor
serv.log post wg
```

Does this still happen with latest nightly?

**Comment by cbnolok** [comment]
Yes actually it appears when a specific compiler optimization (inline functions expansion) is enabled, which happens in the nightly and release builds but not in the debug one, that's a vague but valid starting point nonetheless

**Comment by drk84** [comment]
It works fine now
