### ISSUE TITLE
Revealing after someone step on player while under invis spell

### ISSUE THREAD

**Issue by azmanomer** [Sphereserver/Source-experimental#89]
I just check OSI behaviour and it seems when u are under invis spell and someone step on you. You are not revealed and the person step on you didnt receive any message.

**Comment by nefthon** [comment]
I would add another REVEALF_* flag to modify this behaviour and, in the proccess, a new ARGN2=dwFlags in the @PersonalSpace trigger to modify what flags to reveal (if any) for each character.

**Comment by roberpot** [comment]
@nefthon  has a improvement for this patch to add script trigger overwrite for this behaviour i think.

**Comment by GitMadKing** [comment]
i confirm this was a "old style" feature
with spell and (=POTION) of invisibility 
you can TALK, not revealed when walked over, also loot
with hiding/stealth
can't talk, you are revealed when walked over, can loot
